//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 10:35:14 AM MDT 
//


package com.cognos.developer.schemas.bmt._60._7;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cardinalityEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="cardinalityEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="unknown"/>
 *     &lt;enumeration value="unsupported"/>
 *     &lt;enumeration value="zero"/>
 *     &lt;enumeration value="one"/>
 *     &lt;enumeration value="many"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "cardinalityEnum")
@XmlEnum
public enum CardinalityEnum {


    /**
     * Specifies that the maximum number of rows is not known.
     * 
     */
    @XmlEnumValue("unknown")
    UNKNOWN("unknown"),

    /**
     * Specifies that this feature is not supported.
     * 
     */
    @XmlEnumValue("unsupported")
    UNSUPPORTED("unsupported"),

    /**
     * Specifies that this object has no rows.
     * 
     */
    @XmlEnumValue("zero")
    ZERO("zero"),

    /**
     * Specifies that this object has one row only.
     * 
     */
    @XmlEnumValue("one")
    ONE("one"),

    /**
     * Specifies that this object can have many rows.
     * 
     */
    @XmlEnumValue("many")
    MANY("many");
    private final String value;

    CardinalityEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static com.cognos.developer.schemas.bmt._60._7.CardinalityEnum fromValue(String v) {
        for (com.cognos.developer.schemas.bmt._60._7.CardinalityEnum c: com.cognos.developer.schemas.bmt._60._7.CardinalityEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
