//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 10:35:14 AM MDT 
//


package com.cognos.developer.schemas.bmt._60._7;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cardinalityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cardinalityType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="refobj" type="{http://www.developer.cognos.com/schemas/bmt/60/7}refType"/>
 *         &lt;element name="mincard" type="{http://www.developer.cognos.com/schemas/bmt/60/7}cardinalityEnum"/>
 *         &lt;element name="maxcard" type="{http://www.developer.cognos.com/schemas/bmt/60/7}cardinalityEnum"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cardinalityType", propOrder = {
    "refobj",
    "mincard",
    "maxcard"
})
public class CardinalityType {

    @XmlElement(required = true)
    protected String refobj;
    @XmlElement(required = true)
    protected com.cognos.developer.schemas.bmt._60._7.CardinalityEnum mincard;
    @XmlElement(required = true)
    protected com.cognos.developer.schemas.bmt._60._7.CardinalityEnum maxcard;

    /**
     * Gets the value of the refobj property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefobj() {
        return refobj;
    }

    /**
     * Sets the value of the refobj property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefobj(String value) {
        this.refobj = value;
    }

    /**
     * Gets the value of the mincard property.
     * 
     * @return
     *     possible object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.CardinalityEnum }
     *     
     */
    public com.cognos.developer.schemas.bmt._60._7.CardinalityEnum getMincard() {
        return mincard;
    }

    /**
     * Sets the value of the mincard property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.CardinalityEnum }
     *     
     */
    public void setMincard(com.cognos.developer.schemas.bmt._60._7.CardinalityEnum value) {
        this.mincard = value;
    }

    /**
     * Gets the value of the maxcard property.
     * 
     * @return
     *     possible object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.CardinalityEnum }
     *     
     */
    public com.cognos.developer.schemas.bmt._60._7.CardinalityEnum getMaxcard() {
        return maxcard;
    }

    /**
     * Sets the value of the maxcard property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.CardinalityEnum }
     *     
     */
    public void setMaxcard(com.cognos.developer.schemas.bmt._60._7.CardinalityEnum value) {
        this.maxcard = value;
    }

}
