//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 10:35:14 AM MDT 
//


package com.cognos.developer.schemas.bmt._60._7;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for dataSourceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dataSourceType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.developer.cognos.com/schemas/bmt/60/7}modelObjectType">
 *       &lt;sequence>
 *         &lt;element name="queryProcessing" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *               &lt;enumeration value="databaseOnly"/>
 *               &lt;enumeration value="limitedLocal"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="rollupProcessing" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *               &lt;enumeration value="unspecified"/>
 *               &lt;enumeration value="local"/>
 *               &lt;enumeration value="database"/>
 *               &lt;enumeration value="extended"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="transactionAccessMode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *               &lt;enumeration value="unspecified"/>
 *               &lt;enumeration value="read"/>
 *               &lt;enumeration value="write"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="transactionStatementMode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *               &lt;enumeration value="unspecified"/>
 *               &lt;enumeration value="rollback"/>
 *               &lt;enumeration value="commit"/>
 *               &lt;enumeration value="autocommit"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="cmDataSource" type="{http://www.developer.cognos.com/schemas/bmt/60/7}macroType"/>
 *         &lt;element name="catalog" type="{http://www.developer.cognos.com/schemas/bmt/60/7}macroType" minOccurs="0"/>
 *         &lt;element name="cube" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="schema" type="{http://www.developer.cognos.com/schemas/bmt/60/7}macroType" minOccurs="0"/>
 *         &lt;element name="type">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="queryType" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *                         &lt;enumeration value="relational"/>
 *                         &lt;enumeration value="multidimensional"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="interface" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="functionSetID" type="{http://www.developer.cognos.com/schemas/bmt/60/7}functionSetIDType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="connectionString" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{http://www.developer.cognos.com/schemas/bmt/60/7}aliasTableMapRef" minOccurs="0"/>
 *         &lt;element name="cubeDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cubePath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cubeCreatedOn" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="cubeDataUpdatedOn" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="cubeSchemaUpdatedOn" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="cubeIsOptimized" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="cubeDefaultMeasure" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cubeCurrentPeriod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="suppression" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *               &lt;enumeration value="none"/>
 *               &lt;enumeration value="null"/>
 *               &lt;enumeration value="zero"/>
 *               &lt;enumeration value="nullAndZero"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="attributeDimensionsAsProperties" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dataSourceType", propOrder = {
    "queryProcessing",
    "rollupProcessing",
    "transactionAccessMode",
    "transactionStatementMode",
    "cmDataSource",
    "catalog",
    "cube",
    "schema",
    "type",
    "connectionString",
    "aliasTableMapRef",
    "cubeDescription",
    "cubePath",
    "cubeCreatedOn",
    "cubeDataUpdatedOn",
    "cubeSchemaUpdatedOn",
    "cubeIsOptimized",
    "cubeDefaultMeasure",
    "cubeCurrentPeriod",
    "suppression",
    "attributeDimensionsAsProperties"
})
public class DataSourceType
    extends com.cognos.developer.schemas.bmt._60._7.ModelObjectType
{

    @XmlElement(defaultValue = "databaseOnly")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String queryProcessing;
    @XmlElement(defaultValue = "unspecified")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String rollupProcessing;
    @XmlElement(defaultValue = "unspecified")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String transactionAccessMode;
    @XmlElement(defaultValue = "unspecified")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String transactionStatementMode;
    @XmlElement(required = true)
    protected com.cognos.developer.schemas.bmt._60._7.MacroType cmDataSource;
    protected com.cognos.developer.schemas.bmt._60._7.MacroType catalog;
    protected String cube;
    protected com.cognos.developer.schemas.bmt._60._7.MacroType schema;
    @XmlElement(required = true)
    protected com.cognos.developer.schemas.bmt._60._7.DataSourceType.Type type;
    protected String connectionString;
    protected String aliasTableMapRef;
    protected String cubeDescription;
    protected String cubePath;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar cubeCreatedOn;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar cubeDataUpdatedOn;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar cubeSchemaUpdatedOn;
    protected Boolean cubeIsOptimized;
    protected String cubeDefaultMeasure;
    protected String cubeCurrentPeriod;
    @XmlElement(defaultValue = "none")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String suppression;
    @XmlElement(defaultValue = "true")
    protected Boolean attributeDimensionsAsProperties;

    /**
     * Gets the value of the queryProcessing property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getQueryProcessing() {
        return queryProcessing;
    }

    /**
     * Sets the value of the queryProcessing property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setQueryProcessing(String value) {
        this.queryProcessing = value;
    }

    /**
     * Gets the value of the rollupProcessing property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getRollupProcessing() {
        return rollupProcessing;
    }

    /**
     * Sets the value of the rollupProcessing property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRollupProcessing(String value) {
        this.rollupProcessing = value;
    }

    /**
     * Gets the value of the transactionAccessMode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTransactionAccessMode() {
        return transactionAccessMode;
    }

    /**
     * Sets the value of the transactionAccessMode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTransactionAccessMode(String value) {
        this.transactionAccessMode = value;
    }

    /**
     * Gets the value of the transactionStatementMode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTransactionStatementMode() {
        return transactionStatementMode;
    }

    /**
     * Sets the value of the transactionStatementMode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTransactionStatementMode(String value) {
        this.transactionStatementMode = value;
    }

    /**
     * Gets the value of the cmDataSource property.
     *
     * @return
     *     possible object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.MacroType }
     *
     */
    public com.cognos.developer.schemas.bmt._60._7.MacroType getCmDataSource() {
        return cmDataSource;
    }

    /**
     * Sets the value of the cmDataSource property.
     *
     * @param value
     *     allowed object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.MacroType }
     *
     */
    public void setCmDataSource(com.cognos.developer.schemas.bmt._60._7.MacroType value) {
        this.cmDataSource = value;
    }

    /**
     * Gets the value of the catalog property.
     *
     * @return
     *     possible object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.MacroType }
     *
     */
    public com.cognos.developer.schemas.bmt._60._7.MacroType getCatalog() {
        return catalog;
    }

    /**
     * Sets the value of the catalog property.
     *
     * @param value
     *     allowed object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.MacroType }
     *
     */
    public void setCatalog(com.cognos.developer.schemas.bmt._60._7.MacroType value) {
        this.catalog = value;
    }

    /**
     * Gets the value of the cube property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCube() {
        return cube;
    }

    /**
     * Sets the value of the cube property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCube(String value) {
        this.cube = value;
    }

    /**
     * Gets the value of the schema property.
     *
     * @return
     *     possible object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.MacroType }
     *
     */
    public com.cognos.developer.schemas.bmt._60._7.MacroType getSchema() {
        return schema;
    }

    /**
     * Sets the value of the schema property.
     *
     * @param value
     *     allowed object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.MacroType }
     *
     */
    public void setSchema(com.cognos.developer.schemas.bmt._60._7.MacroType value) {
        this.schema = value;
    }

    /**
     * Gets the value of the type property.
     *
     * @return
     *     possible object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.DataSourceType.Type }
     *
     */
    public com.cognos.developer.schemas.bmt._60._7.DataSourceType.Type getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value
     *     allowed object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.DataSourceType.Type }
     *
     */
    public void setType(com.cognos.developer.schemas.bmt._60._7.DataSourceType.Type value) {
        this.type = value;
    }

    /**
     * Gets the value of the connectionString property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getConnectionString() {
        return connectionString;
    }

    /**
     * Sets the value of the connectionString property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setConnectionString(String value) {
        this.connectionString = value;
    }

    /**
     * References a parameterMap that represents a DB2OLAP or Applix alias table map.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAliasTableMapRef() {
        return aliasTableMapRef;
    }

    /**
     * Sets the value of the aliasTableMapRef property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAliasTableMapRef(String value) {
        this.aliasTableMapRef = value;
    }

    /**
     * Gets the value of the cubeDescription property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCubeDescription() {
        return cubeDescription;
    }

    /**
     * Sets the value of the cubeDescription property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCubeDescription(String value) {
        this.cubeDescription = value;
    }

    /**
     * Gets the value of the cubePath property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCubePath() {
        return cubePath;
    }

    /**
     * Sets the value of the cubePath property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCubePath(String value) {
        this.cubePath = value;
    }

    /**
     * Gets the value of the cubeCreatedOn property.
     *
     * @return
     *     possible object is
     *     {@link javax.xml.datatype.XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getCubeCreatedOn() {
        return cubeCreatedOn;
    }

    /**
     * Sets the value of the cubeCreatedOn property.
     *
     * @param value
     *     allowed object is
     *     {@link javax.xml.datatype.XMLGregorianCalendar }
     *
     */
    public void setCubeCreatedOn(XMLGregorianCalendar value) {
        this.cubeCreatedOn = value;
    }

    /**
     * Gets the value of the cubeDataUpdatedOn property.
     *
     * @return
     *     possible object is
     *     {@link javax.xml.datatype.XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getCubeDataUpdatedOn() {
        return cubeDataUpdatedOn;
    }

    /**
     * Sets the value of the cubeDataUpdatedOn property.
     *
     * @param value
     *     allowed object is
     *     {@link javax.xml.datatype.XMLGregorianCalendar }
     *
     */
    public void setCubeDataUpdatedOn(XMLGregorianCalendar value) {
        this.cubeDataUpdatedOn = value;
    }

    /**
     * Gets the value of the cubeSchemaUpdatedOn property.
     *
     * @return
     *     possible object is
     *     {@link javax.xml.datatype.XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getCubeSchemaUpdatedOn() {
        return cubeSchemaUpdatedOn;
    }

    /**
     * Sets the value of the cubeSchemaUpdatedOn property.
     *
     * @param value
     *     allowed object is
     *     {@link javax.xml.datatype.XMLGregorianCalendar }
     *     
     */
    public void setCubeSchemaUpdatedOn(XMLGregorianCalendar value) {
        this.cubeSchemaUpdatedOn = value;
    }

    /**
     * Gets the value of the cubeIsOptimized property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCubeIsOptimized() {
        return cubeIsOptimized;
    }

    /**
     * Sets the value of the cubeIsOptimized property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCubeIsOptimized(Boolean value) {
        this.cubeIsOptimized = value;
    }

    /**
     * Gets the value of the cubeDefaultMeasure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCubeDefaultMeasure() {
        return cubeDefaultMeasure;
    }

    /**
     * Sets the value of the cubeDefaultMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCubeDefaultMeasure(String value) {
        this.cubeDefaultMeasure = value;
    }

    /**
     * Gets the value of the cubeCurrentPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCubeCurrentPeriod() {
        return cubeCurrentPeriod;
    }

    /**
     * Sets the value of the cubeCurrentPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCubeCurrentPeriod(String value) {
        this.cubeCurrentPeriod = value;
    }

    /**
     * Gets the value of the suppression property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuppression() {
        return suppression;
    }

    /**
     * Sets the value of the suppression property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuppression(String value) {
        this.suppression = value;
    }

    /**
     * Gets the value of the attributeDimensionsAsProperties property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAttributeDimensionsAsProperties() {
        return attributeDimensionsAsProperties;
    }

    /**
     * Sets the value of the attributeDimensionsAsProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAttributeDimensionsAsProperties(Boolean value) {
        this.attributeDimensionsAsProperties = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="queryType" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
     *               &lt;enumeration value="relational"/>
     *               &lt;enumeration value="multidimensional"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="interface" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="functionSetID" type="{http://www.developer.cognos.com/schemas/bmt/60/7}functionSetIDType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "queryType",
        "_interface",
        "functionSetID"
    })
    public static class Type {

        @XmlElement(defaultValue = "relational")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String queryType;
        @XmlElement(name = "interface")
        protected String _interface;
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String functionSetID;

        /**
         * Gets the value of the queryType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getQueryType() {
            return queryType;
        }

        /**
         * Sets the value of the queryType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setQueryType(String value) {
            this.queryType = value;
        }

        /**
         * Gets the value of the interface property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInterface() {
            return _interface;
        }

        /**
         * Sets the value of the interface property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInterface(String value) {
            this._interface = value;
        }

        /**
         * Gets the value of the functionSetID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFunctionSetID() {
            return functionSetID;
        }

        /**
         * Sets the value of the functionSetID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFunctionSetID(String value) {
            this.functionSetID = value;
        }

    }

}
