//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 10:35:14 AM MDT 
//


package com.cognos.developer.schemas.bmt._60._7;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for definitionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="definitionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="dbQuery">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="sources" type="{http://www.developer.cognos.com/schemas/bmt/60/7}dataSourceRefsType"/>
 *                   &lt;element ref="{http://www.developer.cognos.com/schemas/bmt/60/7}generateSQL" minOccurs="0"/>
 *                   &lt;element ref="{http://www.developer.cognos.com/schemas/bmt/60/7}sql"/>
 *                   &lt;element name="key" type="{http://www.developer.cognos.com/schemas/bmt/60/7}keyType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="index" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="unique" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="queryItems_collection" type="{http://www.developer.cognos.com/schemas/bmt/60/7}refCollectionType"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element ref="{http://www.developer.cognos.com/schemas/bmt/60/7}filters" minOccurs="0"/>
 *                   &lt;element name="tableType" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *                         &lt;enumeration value="table"/>
 *                         &lt;enumeration value="view"/>
 *                         &lt;enumeration value="nonTransparentTable"/>
 *                         &lt;enumeration value="unknown"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="multiDb" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="mdQuery">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="sources" type="{http://www.developer.cognos.com/schemas/bmt/60/7}dataSourceRefsType"/>
 *                   &lt;element name="mdDimension" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element ref="{http://www.developer.cognos.com/schemas/bmt/60/7}filters" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="modelQuery">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.developer.cognos.com/schemas/bmt/60/7}generateSQL" minOccurs="0"/>
 *                   &lt;element name="sql" type="{http://www.developer.cognos.com/schemas/bmt/60/7}sqlType"/>
 *                   &lt;element name="relationships" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                             &lt;element name="relationshipDefinition">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;choice>
 *                                       &lt;element name="refobj" type="{http://www.developer.cognos.com/schemas/bmt/60/7}refType"/>
 *                                       &lt;element name="embeddedRelationship">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;group ref="{http://www.developer.cognos.com/schemas/bmt/60/7}relationshipProperties"/>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/choice>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element ref="{http://www.developer.cognos.com/schemas/bmt/60/7}filters" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="storedProcedure" type="{http://www.developer.cognos.com/schemas/bmt/60/7}storedProcedureType"/>
 *         &lt;element name="queryOperation">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="querySubjectRefs">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="refobj" type="{http://www.developer.cognos.com/schemas/bmt/60/7}refType" maxOccurs="2" minOccurs="2"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="setOperation">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *                         &lt;enumeration value="UNION"/>
 *                         &lt;enumeration value="INTERSECT"/>
 *                         &lt;enumeration value="EXCEPT"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="duplicates">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *                         &lt;enumeration value="remove"/>
 *                         &lt;enumeration value="preserve"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element ref="{http://www.developer.cognos.com/schemas/bmt/60/7}filters" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "definitionType", propOrder = {
    "dbQuery",
    "mdQuery",
    "modelQuery",
    "storedProcedure",
    "queryOperation"
})
public class DefinitionType {

    protected com.cognos.developer.schemas.bmt._60._7.DefinitionType.DbQuery dbQuery;
    protected com.cognos.developer.schemas.bmt._60._7.DefinitionType.MdQuery mdQuery;
    protected com.cognos.developer.schemas.bmt._60._7.DefinitionType.ModelQuery modelQuery;
    protected StoredProcedureType storedProcedure;
    protected com.cognos.developer.schemas.bmt._60._7.DefinitionType.QueryOperation queryOperation;

    /**
     * Gets the value of the dbQuery property.
     *
     * @return
     *     possible object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.DefinitionType.DbQuery }
     *
     */
    public com.cognos.developer.schemas.bmt._60._7.DefinitionType.DbQuery getDbQuery() {
        return dbQuery;
    }

    /**
     * Sets the value of the dbQuery property.
     *
     * @param value
     *     allowed object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.DefinitionType.DbQuery }
     *
     */
    public void setDbQuery(com.cognos.developer.schemas.bmt._60._7.DefinitionType.DbQuery value) {
        this.dbQuery = value;
    }

    /**
     * Gets the value of the mdQuery property.
     *
     * @return
     *     possible object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.DefinitionType.MdQuery }
     *
     */
    public com.cognos.developer.schemas.bmt._60._7.DefinitionType.MdQuery getMdQuery() {
        return mdQuery;
    }

    /**
     * Sets the value of the mdQuery property.
     *
     * @param value
     *     allowed object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.DefinitionType.MdQuery }
     *
     */
    public void setMdQuery(com.cognos.developer.schemas.bmt._60._7.DefinitionType.MdQuery value) {
        this.mdQuery = value;
    }

    /**
     * Gets the value of the modelQuery property.
     *
     * @return
     *     possible object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.DefinitionType.ModelQuery }
     *
     */
    public com.cognos.developer.schemas.bmt._60._7.DefinitionType.ModelQuery getModelQuery() {
        return modelQuery;
    }

    /**
     * Sets the value of the modelQuery property.
     *
     * @param value
     *     allowed object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.DefinitionType.ModelQuery }
     *
     */
    public void setModelQuery(com.cognos.developer.schemas.bmt._60._7.DefinitionType.ModelQuery value) {
        this.modelQuery = value;
    }

    /**
     * Gets the value of the storedProcedure property.
     *
     * @return
     *     possible object is
     *     {@link StoredProcedureType }
     *
     */
    public StoredProcedureType getStoredProcedure() {
        return storedProcedure;
    }

    /**
     * Sets the value of the storedProcedure property.
     *
     * @param value
     *     allowed object is
     *     {@link StoredProcedureType }
     *
     */
    public void setStoredProcedure(StoredProcedureType value) {
        this.storedProcedure = value;
    }

    /**
     * Gets the value of the queryOperation property.
     *
     * @return
     *     possible object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.DefinitionType.QueryOperation }
     *
     */
    public com.cognos.developer.schemas.bmt._60._7.DefinitionType.QueryOperation getQueryOperation() {
        return queryOperation;
    }

    /**
     * Sets the value of the queryOperation property.
     *
     * @param value
     *     allowed object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.DefinitionType.QueryOperation }
     *
     */
    public void setQueryOperation(com.cognos.developer.schemas.bmt._60._7.DefinitionType.QueryOperation value) {
        this.queryOperation = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="sources" type="{http://www.developer.cognos.com/schemas/bmt/60/7}dataSourceRefsType"/>
     *         &lt;element ref="{http://www.developer.cognos.com/schemas/bmt/60/7}generateSQL" minOccurs="0"/>
     *         &lt;element ref="{http://www.developer.cognos.com/schemas/bmt/60/7}sql"/>
     *         &lt;element name="key" type="{http://www.developer.cognos.com/schemas/bmt/60/7}keyType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="index" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="unique" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="queryItems_collection" type="{http://www.developer.cognos.com/schemas/bmt/60/7}refCollectionType"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element ref="{http://www.developer.cognos.com/schemas/bmt/60/7}filters" minOccurs="0"/>
     *         &lt;element name="tableType" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
     *               &lt;enumeration value="table"/>
     *               &lt;enumeration value="view"/>
     *               &lt;enumeration value="nonTransparentTable"/>
     *               &lt;enumeration value="unknown"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="multiDb" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "sources",
        "generateSQL",
        "sql",
        "key",
        "index",
        "filters",
        "tableType"
    })
    public static class DbQuery {

        @XmlElement(required = true)
        protected DataSourceRefsType sources;
        @XmlElement(defaultValue = "minimized")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String generateSQL;
        @XmlElement(required = true)
        protected SqlType sql;
        protected List<KeyType> key;
        protected List<com.cognos.developer.schemas.bmt._60._7.DefinitionType.DbQuery.Index> index;
        protected Filters filters;
        @XmlElement(defaultValue = "unknown")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String tableType;
        @XmlAttribute(name = "multiDb")
        protected Boolean multiDb;

        /**
         * Gets the value of the sources property.
         *
         * @return
         *     possible object is
         *     {@link DataSourceRefsType }
         *
         */
        public DataSourceRefsType getSources() {
            return sources;
        }

        /**
         * Sets the value of the sources property.
         *
         * @param value
         *     allowed object is
         *     {@link DataSourceRefsType }
         *
         */
        public void setSources(DataSourceRefsType value) {
            this.sources = value;
        }

        /**
         * Gets the value of the generateSQL property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getGenerateSQL() {
            return generateSQL;
        }

        /**
         * Sets the value of the generateSQL property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setGenerateSQL(String value) {
            this.generateSQL = value;
        }

        /**
         * Gets the value of the sql property.
         *
         * @return
         *     possible object is
         *     {@link SqlType }
         *
         */
        public SqlType getSql() {
            return sql;
        }

        /**
         * Sets the value of the sql property.
         *
         * @param value
         *     allowed object is
         *     {@link SqlType }
         *
         */
        public void setSql(SqlType value) {
            this.sql = value;
        }

        /**
         * Gets the value of the key property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the key property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getKey().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link KeyType }
         *
         *
         */
        public List<KeyType> getKey() {
            if (key == null) {
                key = new ArrayList<KeyType>();
            }
            return this.key;
        }

        /**
         * Gets the value of the index property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the index property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getIndex().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link com.cognos.developer.schemas.bmt._60._7.DefinitionType.DbQuery.Index }
         *
         *
         */
        public List<com.cognos.developer.schemas.bmt._60._7.DefinitionType.DbQuery.Index> getIndex() {
            if (index == null) {
                index = new ArrayList<com.cognos.developer.schemas.bmt._60._7.DefinitionType.DbQuery.Index>();
            }
            return this.index;
        }

        /**
         * Gets the value of the filters property.
         *
         * @return
         *     possible object is
         *     {@link Filters }
         *
         */
        public Filters getFilters() {
            return filters;
        }

        /**
         * Sets the value of the filters property.
         *
         * @param value
         *     allowed object is
         *     {@link Filters }
         *
         */
        public void setFilters(Filters value) {
            this.filters = value;
        }

        /**
         * Gets the value of the tableType property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getTableType() {
            return tableType;
        }

        /**
         * Sets the value of the tableType property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setTableType(String value) {
            this.tableType = value;
        }

        /**
         * Gets the value of the multiDb property.
         *
         * @return
         *     possible object is
         *     {@link Boolean }
         *
         */
        public boolean isMultiDb() {
            if (multiDb == null) {
                return false;
            } else {
                return multiDb;
            }
        }

        /**
         * Sets the value of the multiDb property.
         *
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *
         */
        public void setMultiDb(Boolean value) {
            this.multiDb = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="unique" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="queryItems_collection" type="{http://www.developer.cognos.com/schemas/bmt/60/7}refCollectionType"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "unique",
            "queryItemsCollection"
        })
        public static class Index {

            protected boolean unique;
            @XmlElement(name = "queryItems_collection", required = true)
            protected RefCollectionType queryItemsCollection;

            /**
             * Gets the value of the unique property.
             *
             */
            public boolean isUnique() {
                return unique;
            }

            /**
             * Sets the value of the unique property.
             *
             */
            public void setUnique(boolean value) {
                this.unique = value;
            }

            /**
             * Gets the value of the queryItemsCollection property.
             *
             * @return
             *     possible object is
             *     {@link RefCollectionType }
             *
             */
            public RefCollectionType getQueryItemsCollection() {
                return queryItemsCollection;
            }

            /**
             * Sets the value of the queryItemsCollection property.
             *
             * @param value
             *     allowed object is
             *     {@link RefCollectionType }
             *
             */
            public void setQueryItemsCollection(RefCollectionType value) {
                this.queryItemsCollection = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="sources" type="{http://www.developer.cognos.com/schemas/bmt/60/7}dataSourceRefsType"/>
     *         &lt;element name="mdDimension" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element ref="{http://www.developer.cognos.com/schemas/bmt/60/7}filters" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "sources",
        "mdDimension",
        "filters"
    })
    public static class MdQuery {

        @XmlElement(required = true)
        protected DataSourceRefsType sources;
        protected String mdDimension;
        protected Filters filters;

        /**
         * Gets the value of the sources property.
         *
         * @return
         *     possible object is
         *     {@link DataSourceRefsType }
         *
         */
        public DataSourceRefsType getSources() {
            return sources;
        }

        /**
         * Sets the value of the sources property.
         *
         * @param value
         *     allowed object is
         *     {@link DataSourceRefsType }
         *
         */
        public void setSources(DataSourceRefsType value) {
            this.sources = value;
        }

        /**
         * Gets the value of the mdDimension property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getMdDimension() {
            return mdDimension;
        }

        /**
         * Sets the value of the mdDimension property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setMdDimension(String value) {
            this.mdDimension = value;
        }

        /**
         * Gets the value of the filters property.
         *
         * @return
         *     possible object is
         *     {@link Filters }
         *
         */
        public Filters getFilters() {
            return filters;
        }

        /**
         * Sets the value of the filters property.
         *
         * @param value
         *     allowed object is
         *     {@link Filters }
         *
         */
        public void setFilters(Filters value) {
            this.filters = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.developer.cognos.com/schemas/bmt/60/7}generateSQL" minOccurs="0"/>
     *         &lt;element name="sql" type="{http://www.developer.cognos.com/schemas/bmt/60/7}sqlType"/>
     *         &lt;element name="relationships" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *                   &lt;element name="relationshipDefinition">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;choice>
     *                             &lt;element name="refobj" type="{http://www.developer.cognos.com/schemas/bmt/60/7}refType"/>
     *                             &lt;element name="embeddedRelationship">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;group ref="{http://www.developer.cognos.com/schemas/bmt/60/7}relationshipProperties"/>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/choice>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element ref="{http://www.developer.cognos.com/schemas/bmt/60/7}filters" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "generateSQL",
        "sql",
        "relationships",
        "filters"
    })
    public static class ModelQuery {

        @XmlElement(defaultValue = "minimized")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String generateSQL;
        @XmlElement(required = true)
        protected SqlType sql;
        protected com.cognos.developer.schemas.bmt._60._7.DefinitionType.ModelQuery.Relationships relationships;
        protected Filters filters;

        /**
         * Gets the value of the generateSQL property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getGenerateSQL() {
            return generateSQL;
        }

        /**
         * Sets the value of the generateSQL property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setGenerateSQL(String value) {
            this.generateSQL = value;
        }

        /**
         * Gets the value of the sql property.
         *
         * @return
         *     possible object is
         *     {@link SqlType }
         *
         */
        public SqlType getSql() {
            return sql;
        }

        /**
         * Sets the value of the sql property.
         *
         * @param value
         *     allowed object is
         *     {@link SqlType }
         *
         */
        public void setSql(SqlType value) {
            this.sql = value;
        }

        /**
         * Gets the value of the relationships property.
         *
         * @return
         *     possible object is
         *     {@link com.cognos.developer.schemas.bmt._60._7.DefinitionType.ModelQuery.Relationships }
         *
         */
        public com.cognos.developer.schemas.bmt._60._7.DefinitionType.ModelQuery.Relationships getRelationships() {
            return relationships;
        }

        /**
         * Sets the value of the relationships property.
         *
         * @param value
         *     allowed object is
         *     {@link com.cognos.developer.schemas.bmt._60._7.DefinitionType.ModelQuery.Relationships }
         *
         */
        public void setRelationships(com.cognos.developer.schemas.bmt._60._7.DefinitionType.ModelQuery.Relationships value) {
            this.relationships = value;
        }

        /**
         * Gets the value of the filters property.
         *
         * @return
         *     possible object is
         *     {@link Filters }
         *
         */
        public Filters getFilters() {
            return filters;
        }

        /**
         * Sets the value of the filters property.
         *
         * @param value
         *     allowed object is
         *     {@link Filters }
         *
         */
        public void setFilters(Filters value) {
            this.filters = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
         *         &lt;element name="relationshipDefinition">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;choice>
         *                   &lt;element name="refobj" type="{http://www.developer.cognos.com/schemas/bmt/60/7}refType"/>
         *                   &lt;element name="embeddedRelationship">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;group ref="{http://www.developer.cognos.com/schemas/bmt/60/7}relationshipProperties"/>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/choice>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "relationshipDefinition"
        })
        public static class Relationships {

            protected List<com.cognos.developer.schemas.bmt._60._7.DefinitionType.ModelQuery.Relationships.RelationshipDefinition> relationshipDefinition;

            /**
             * Gets the value of the relationshipDefinition property.
             *
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the relationshipDefinition property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getRelationshipDefinition().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link com.cognos.developer.schemas.bmt._60._7.DefinitionType.ModelQuery.Relationships.RelationshipDefinition }
             *
             *
             */
            public List<com.cognos.developer.schemas.bmt._60._7.DefinitionType.ModelQuery.Relationships.RelationshipDefinition> getRelationshipDefinition() {
                if (relationshipDefinition == null) {
                    relationshipDefinition = new ArrayList<com.cognos.developer.schemas.bmt._60._7.DefinitionType.ModelQuery.Relationships.RelationshipDefinition>();
                }
                return this.relationshipDefinition;
            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;choice>
             *         &lt;element name="refobj" type="{http://www.developer.cognos.com/schemas/bmt/60/7}refType"/>
             *         &lt;element name="embeddedRelationship">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;group ref="{http://www.developer.cognos.com/schemas/bmt/60/7}relationshipProperties"/>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/choice>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "refobj",
                "embeddedRelationship"
            })
            public static class RelationshipDefinition {

                protected String refobj;
                protected com.cognos.developer.schemas.bmt._60._7.DefinitionType.ModelQuery.Relationships.RelationshipDefinition.EmbeddedRelationship embeddedRelationship;

                /**
                 * Gets the value of the refobj property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getRefobj() {
                    return refobj;
                }

                /**
                 * Sets the value of the refobj property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setRefobj(String value) {
                    this.refobj = value;
                }

                /**
                 * Gets the value of the embeddedRelationship property.
                 *
                 * @return
                 *     possible object is
                 *     {@link com.cognos.developer.schemas.bmt._60._7.DefinitionType.ModelQuery.Relationships.RelationshipDefinition.EmbeddedRelationship }
                 *
                 */
                public com.cognos.developer.schemas.bmt._60._7.DefinitionType.ModelQuery.Relationships.RelationshipDefinition.EmbeddedRelationship getEmbeddedRelationship() {
                    return embeddedRelationship;
                }

                /**
                 * Sets the value of the embeddedRelationship property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link com.cognos.developer.schemas.bmt._60._7.DefinitionType.ModelQuery.Relationships.RelationshipDefinition.EmbeddedRelationship }
                 *
                 */
                public void setEmbeddedRelationship(com.cognos.developer.schemas.bmt._60._7.DefinitionType.ModelQuery.Relationships.RelationshipDefinition.EmbeddedRelationship value) {
                    this.embeddedRelationship = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 *
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 *
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;group ref="{http://www.developer.cognos.com/schemas/bmt/60/7}relationshipProperties"/>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 *
                 *
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "expression",
                    "sql",
                    "left",
                    "right",
                    "joinFilterType"
                })
                public static class EmbeddedRelationship {

                    @XmlElement(required = true)
                    protected ExpressionType expression;
                    protected SqlType sql;
                    @XmlElement(required = true)
                    protected CardinalityType left;
                    @XmlElement(required = true)
                    protected CardinalityType right;
                    @XmlElement(defaultValue = "none")
                    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
                    protected String joinFilterType;

                    /**
                     * Gets the value of the expression property.
                     *
                     * @return
                     *     possible object is
                     *     {@link ExpressionType }
                     *
                     */
                    public ExpressionType getExpression() {
                        return expression;
                    }

                    /**
                     * Sets the value of the expression property.
                     *
                     * @param value
                     *     allowed object is
                     *     {@link ExpressionType }
                     *
                     */
                    public void setExpression(ExpressionType value) {
                        this.expression = value;
                    }

                    /**
                     * Gets the value of the sql property.
                     *
                     * @return
                     *     possible object is
                     *     {@link SqlType }
                     *
                     */
                    public SqlType getSql() {
                        return sql;
                    }

                    /**
                     * Sets the value of the sql property.
                     *
                     * @param value
                     *     allowed object is
                     *     {@link SqlType }
                     *
                     */
                    public void setSql(SqlType value) {
                        this.sql = value;
                    }

                    /**
                     * Gets the value of the left property.
                     *
                     * @return
                     *     possible object is
                     *     {@link CardinalityType }
                     *
                     */
                    public CardinalityType getLeft() {
                        return left;
                    }

                    /**
                     * Sets the value of the left property.
                     *
                     * @param value
                     *     allowed object is
                     *     {@link CardinalityType }
                     *
                     */
                    public void setLeft(CardinalityType value) {
                        this.left = value;
                    }

                    /**
                     * Gets the value of the right property.
                     *
                     * @return
                     *     possible object is
                     *     {@link CardinalityType }
                     *
                     */
                    public CardinalityType getRight() {
                        return right;
                    }

                    /**
                     * Sets the value of the right property.
                     *
                     * @param value
                     *     allowed object is
                     *     {@link CardinalityType }
                     *
                     */
                    public void setRight(CardinalityType value) {
                        this.right = value;
                    }

                    /**
                     * Gets the value of the joinFilterType property.
                     *
                     * @return
                     *     possible object is
                     *     {@link String }
                     *
                     */
                    public String getJoinFilterType() {
                        return joinFilterType;
                    }

                    /**
                     * Sets the value of the joinFilterType property.
                     *
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *
                     */
                    public void setJoinFilterType(String value) {
                        this.joinFilterType = value;
                    }

                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="querySubjectRefs">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="refobj" type="{http://www.developer.cognos.com/schemas/bmt/60/7}refType" maxOccurs="2" minOccurs="2"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="setOperation">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
     *               &lt;enumeration value="UNION"/>
     *               &lt;enumeration value="INTERSECT"/>
     *               &lt;enumeration value="EXCEPT"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="duplicates">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
     *               &lt;enumeration value="remove"/>
     *               &lt;enumeration value="preserve"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element ref="{http://www.developer.cognos.com/schemas/bmt/60/7}filters" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "querySubjectRefs",
        "setOperation",
        "duplicates",
        "filters"
    })
    public static class QueryOperation {

        @XmlElement(required = true)
        protected com.cognos.developer.schemas.bmt._60._7.DefinitionType.QueryOperation.QuerySubjectRefs querySubjectRefs;
        @XmlElement(required = true, defaultValue = "UNION")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String setOperation;
        @XmlElement(required = true, defaultValue = "remove")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String duplicates;
        protected Filters filters;

        /**
         * Gets the value of the querySubjectRefs property.
         *
         * @return
         *     possible object is
         *     {@link com.cognos.developer.schemas.bmt._60._7.DefinitionType.QueryOperation.QuerySubjectRefs }
         *
         */
        public com.cognos.developer.schemas.bmt._60._7.DefinitionType.QueryOperation.QuerySubjectRefs getQuerySubjectRefs() {
            return querySubjectRefs;
        }

        /**
         * Sets the value of the querySubjectRefs property.
         *
         * @param value
         *     allowed object is
         *     {@link com.cognos.developer.schemas.bmt._60._7.DefinitionType.QueryOperation.QuerySubjectRefs }
         *
         */
        public void setQuerySubjectRefs(com.cognos.developer.schemas.bmt._60._7.DefinitionType.QueryOperation.QuerySubjectRefs value) {
            this.querySubjectRefs = value;
        }

        /**
         * Gets the value of the setOperation property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSetOperation() {
            return setOperation;
        }

        /**
         * Sets the value of the setOperation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSetOperation(String value) {
            this.setOperation = value;
        }

        /**
         * Gets the value of the duplicates property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDuplicates() {
            return duplicates;
        }

        /**
         * Sets the value of the duplicates property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDuplicates(String value) {
            this.duplicates = value;
        }

        /**
         * Gets the value of the filters property.
         * 
         * @return
         *     possible object is
         *     {@link Filters }
         *     
         */
        public Filters getFilters() {
            return filters;
        }

        /**
         * Sets the value of the filters property.
         * 
         * @param value
         *     allowed object is
         *     {@link Filters }
         *     
         */
        public void setFilters(Filters value) {
            this.filters = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="refobj" type="{http://www.developer.cognos.com/schemas/bmt/60/7}refType" maxOccurs="2" minOccurs="2"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "refobj"
        })
        public static class QuerySubjectRefs {

            @XmlElement(required = true)
            protected List<String> refobj;

            /**
             * Gets the value of the refobj property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the refobj property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getRefobj().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getRefobj() {
                if (refobj == null) {
                    refobj = new ArrayList<String>();
                }
                return this.refobj;
            }

        }

    }

}
