//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 10:35:14 AM MDT 
//


package com.cognos.developer.schemas.bmt._60._7;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * Captures the relationship between a key and the attributes uniquely described by the key.
 * 
 * <p>Java class for _determinantType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="_determinantType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element ref="{http://www.developer.cognos.com/schemas/bmt/60/7}property" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="externalName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="externalOrdinal" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="keyref" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="key">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;extension base="{http://www.developer.cognos.com/schemas/bmt/60/7}keyType">
 *                   &lt;attribute name="isUniqueKey" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *                 &lt;/extension>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *         &lt;element name="attributes" type="{http://www.developer.cognos.com/schemas/bmt/60/7}refCollectionType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "_determinantType", propOrder = {
    "name",
    "property",
    "externalName",
    "externalOrdinal",
    "keyref",
    "key",
    "attributes"
})
public class DeterminantType2 {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String name;
    protected List<Property> property;
    protected String externalName;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger externalOrdinal;
    protected String keyref;
    protected com.cognos.developer.schemas.bmt._60._7.DeterminantType2.Key key;
    @XmlElement(required = true)
    protected RefCollectionType attributes;

    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the property property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the property property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProperty().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Property }
     *
     *
     */
    public List<Property> getProperty() {
        if (property == null) {
            property = new ArrayList<Property>();
        }
        return this.property;
    }

    /**
     * Gets the value of the externalName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getExternalName() {
        return externalName;
    }

    /**
     * Sets the value of the externalName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setExternalName(String value) {
        this.externalName = value;
    }

    /**
     * Gets the value of the externalOrdinal property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getExternalOrdinal() {
        return externalOrdinal;
    }

    /**
     * Sets the value of the externalOrdinal property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setExternalOrdinal(BigInteger value) {
        this.externalOrdinal = value;
    }

    /**
     * Gets the value of the keyref property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getKeyref() {
        return keyref;
    }

    /**
     * Sets the value of the keyref property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setKeyref(String value) {
        this.keyref = value;
    }

    /**
     * Gets the value of the key property.
     *
     * @return
     *     possible object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.DeterminantType2 .Key }
     *
     */
    public com.cognos.developer.schemas.bmt._60._7.DeterminantType2.Key getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     *
     * @param value
     *     allowed object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.DeterminantType2 .Key }
     *
     */
    public void setKey(com.cognos.developer.schemas.bmt._60._7.DeterminantType2.Key value) {
        this.key = value;
    }

    /**
     * Gets the value of the attributes property.
     * 
     * @return
     *     possible object is
     *     {@link RefCollectionType }
     *     
     */
    public RefCollectionType getAttributes() {
        return attributes;
    }

    /**
     * Sets the value of the attributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link RefCollectionType }
     *     
     */
    public void setAttributes(RefCollectionType value) {
        this.attributes = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.developer.cognos.com/schemas/bmt/60/7}keyType">
     *       &lt;attribute name="isUniqueKey" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Key
        extends com.cognos.developer.schemas.bmt._60._7.KeyType
    {

        @XmlAttribute(name = "isUniqueKey")
        protected Boolean isUniqueKey;

        /**
         * Gets the value of the isUniqueKey property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isIsUniqueKey() {
            if (isUniqueKey == null) {
                return false;
            } else {
                return isUniqueKey;
            }
        }

        /**
         * Sets the value of the isUniqueKey property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setIsUniqueKey(Boolean value) {
            this.isUniqueKey = value;
        }

    }

}
