//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 10:35:14 AM MDT 
//


package com.cognos.developer.schemas.bmt._60._7;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.developer.cognos.com/schemas/bmt/60/7}querySubjectType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.developer.cognos.com/schemas/bmt/60/7}dimensionProperties"/>
 *         &lt;choice>
 *           &lt;group ref="{http://www.developer.cognos.com/schemas/bmt/60/7}measureDimensionItems" maxOccurs="unbounded"/>
 *           &lt;group ref="{http://www.developer.cognos.com/schemas/bmt/60/7}memberDimension"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "type",
    "membersRollup",
    "sortMembersMetadata",
    "sortMembersData",
    "sortMembersAndEnableMrf",
    "aliasTableMapRef",
    "measureDimensionItems",
    "defaultHierarchy",
    "hierarchyOrHierarchyFolder"
})
@XmlRootElement(name = "dimension")
public class Dimension
    extends com.cognos.developer.schemas.bmt._60._7.QuerySubjectType
{

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String type;
    @XmlElement(defaultValue = "true")
    protected Boolean membersRollup;
    @XmlElement(defaultValue = "false")
    protected Boolean sortMembersMetadata;
    @XmlElement(defaultValue = "false")
    protected Boolean sortMembersData;
    @XmlElement(defaultValue = "false")
    protected Boolean sortMembersAndEnableMrf;
    protected String aliasTableMapRef;
    @XmlElements({
        @XmlElement(name = "measure", type = Measure.class),
        @XmlElement(name = "measureFolder", type = MeasureFolder.class),
        @XmlElement(name = "queryItem", type = QueryItem.class),
        @XmlElement(name = "queryItemFolder", type = com.cognos.developer.schemas.bmt._60._7.QueryItemFolderType.class)
    })
    protected List<com.cognos.developer.schemas.bmt._60._7.ReportObjectType> measureDimensionItems;
    protected String defaultHierarchy;
    @XmlElements({
        @XmlElement(name = "hierarchy", type = Hierarchy.class),
        @XmlElement(name = "hierarchyFolder", type = HierarchyFolder.class)
    })
    protected List<com.cognos.developer.schemas.bmt._60._7.ReportObjectType> hierarchyOrHierarchyFolder;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the membersRollup property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMembersRollup() {
        return membersRollup;
    }

    /**
     * Sets the value of the membersRollup property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMembersRollup(Boolean value) {
        this.membersRollup = value;
    }

    /**
     * Gets the value of the sortMembersMetadata property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSortMembersMetadata() {
        return sortMembersMetadata;
    }

    /**
     * Sets the value of the sortMembersMetadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSortMembersMetadata(Boolean value) {
        this.sortMembersMetadata = value;
    }

    /**
     * Gets the value of the sortMembersData property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSortMembersData() {
        return sortMembersData;
    }

    /**
     * Sets the value of the sortMembersData property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSortMembersData(Boolean value) {
        this.sortMembersData = value;
    }

    /**
     * Gets the value of the sortMembersAndEnableMrf property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSortMembersAndEnableMrf() {
        return sortMembersAndEnableMrf;
    }

    /**
     * Sets the value of the sortMembersAndEnableMrf property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSortMembersAndEnableMrf(Boolean value) {
        this.sortMembersAndEnableMrf = value;
    }

    /**
     * Gets the value of the aliasTableMapRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAliasTableMapRef() {
        return aliasTableMapRef;
    }

    /**
     * Sets the value of the aliasTableMapRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAliasTableMapRef(String value) {
        this.aliasTableMapRef = value;
    }

    /**
     * Gets the value of the measureDimensionItems property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the measureDimensionItems property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMeasureDimensionItems().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Measure }
     * {@link MeasureFolder }
     * {@link QueryItem }
     * {@link com.cognos.developer.schemas.bmt._60._7.QueryItemFolderType }
     * 
     * 
     */
    public List<com.cognos.developer.schemas.bmt._60._7.ReportObjectType> getMeasureDimensionItems() {
        if (measureDimensionItems == null) {
            measureDimensionItems = new ArrayList<com.cognos.developer.schemas.bmt._60._7.ReportObjectType>();
        }
        return this.measureDimensionItems;
    }

    /**
     * Gets the value of the defaultHierarchy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultHierarchy() {
        return defaultHierarchy;
    }

    /**
     * Sets the value of the defaultHierarchy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultHierarchy(String value) {
        this.defaultHierarchy = value;
    }

    /**
     * Gets the value of the hierarchyOrHierarchyFolder property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hierarchyOrHierarchyFolder property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHierarchyOrHierarchyFolder().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Hierarchy }
     * {@link HierarchyFolder }
     * 
     * 
     */
    public List<com.cognos.developer.schemas.bmt._60._7.ReportObjectType> getHierarchyOrHierarchyFolder() {
        if (hierarchyOrHierarchyFolder == null) {
            hierarchyOrHierarchyFolder = new ArrayList<com.cognos.developer.schemas.bmt._60._7.ReportObjectType>();
        }
        return this.hierarchyOrHierarchyFolder;
    }

}
