//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 10:35:14 AM MDT 
//


package com.cognos.developer.schemas.bmt._60._7;

import javax.xml.bind.annotation.*;


/**
 * Note: The result type of a filter expression must be Boolean.
 * 
 * <p>Java class for filterType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="filterType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.developer.cognos.com/schemas/bmt/60/7}reportObjectType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.developer.cognos.com/schemas/bmt/60/7}expression"/>
 *       &lt;/sequence>
 *       &lt;attribute name="status" type="{http://www.developer.cognos.com/schemas/bmt/60/7}statusType" default="valid" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "filterType", propOrder = {
    "expression"
})
public class FilterType
    extends ReportObjectType
{

    @XmlElement(required = true)
    protected com.cognos.developer.schemas.bmt._60._7.ExpressionType expression;
    @XmlAttribute(name = "status")
    protected StatusType status;

    /**
     * Gets the value of the expression property.
     * 
     * @return
     *     possible object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.ExpressionType }
     *     
     */
    public com.cognos.developer.schemas.bmt._60._7.ExpressionType getExpression() {
        return expression;
    }

    /**
     * Sets the value of the expression property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.ExpressionType }
     *     
     */
    public void setExpression(com.cognos.developer.schemas.bmt._60._7.ExpressionType value) {
        this.expression = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link StatusType }
     *     
     */
    public StatusType getStatus() {
        if (status == null) {
            return StatusType.VALID;
        } else {
            return status;
        }
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusType }
     *     
     */
    public void setStatus(StatusType value) {
        this.status = value;
    }

}
