//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 10:35:14 AM MDT 
//


package com.cognos.developer.schemas.bmt._60._7;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="filterDefinition">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="refobj" type="{http://www.developer.cognos.com/schemas/bmt/60/7}refType"/>
 *                   &lt;sequence>
 *                     &lt;element name="displayName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                     &lt;element ref="{http://www.developer.cognos.com/schemas/bmt/60/7}expression"/>
 *                   &lt;/sequence>
 *                 &lt;/choice>
 *                 &lt;attribute name="apply" default="always">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *                       &lt;enumeration value="always"/>
 *                       &lt;enumeration value="asNeeded"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "filterDefinition"
})
@XmlRootElement(name = "filters")
public class Filters {

    protected List<com.cognos.developer.schemas.bmt._60._7.Filters.FilterDefinition> filterDefinition;

    /**
     * Gets the value of the filterDefinition property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the filterDefinition property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFilterDefinition().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link com.cognos.developer.schemas.bmt._60._7.Filters.FilterDefinition }
     *
     *
     */
    public List<com.cognos.developer.schemas.bmt._60._7.Filters.FilterDefinition> getFilterDefinition() {
        if (filterDefinition == null) {
            filterDefinition = new ArrayList<com.cognos.developer.schemas.bmt._60._7.Filters.FilterDefinition>();
        }
        return this.filterDefinition;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="refobj" type="{http://www.developer.cognos.com/schemas/bmt/60/7}refType"/>
     *         &lt;sequence>
     *           &lt;element name="displayName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *           &lt;element ref="{http://www.developer.cognos.com/schemas/bmt/60/7}expression"/>
     *         &lt;/sequence>
     *       &lt;/choice>
     *       &lt;attribute name="apply" default="always">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
     *             &lt;enumeration value="always"/>
     *             &lt;enumeration value="asNeeded"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "refobj",
        "displayName",
        "expression"
    })
    public static class FilterDefinition {

        protected String refobj;
        protected String displayName;
        protected com.cognos.developer.schemas.bmt._60._7.ExpressionType expression;
        @XmlAttribute(name = "apply")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String apply;

        /**
         * Gets the value of the refobj property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRefobj() {
            return refobj;
        }

        /**
         * Sets the value of the refobj property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRefobj(String value) {
            this.refobj = value;
        }

        /**
         * Gets the value of the displayName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDisplayName() {
            return displayName;
        }

        /**
         * Sets the value of the displayName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDisplayName(String value) {
            this.displayName = value;
        }

        /**
         * Gets the value of the expression property.
         * 
         * @return
         *     possible object is
         *     {@link com.cognos.developer.schemas.bmt._60._7.ExpressionType }
         *     
         */
        public com.cognos.developer.schemas.bmt._60._7.ExpressionType getExpression() {
            return expression;
        }

        /**
         * Sets the value of the expression property.
         * 
         * @param value
         *     allowed object is
         *     {@link com.cognos.developer.schemas.bmt._60._7.ExpressionType }
         *     
         */
        public void setExpression(com.cognos.developer.schemas.bmt._60._7.ExpressionType value) {
            this.expression = value;
        }

        /**
         * Gets the value of the apply property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getApply() {
            if (apply == null) {
                return "always";
            } else {
                return apply;
            }
        }

        /**
         * Sets the value of the apply property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setApply(String value) {
            this.apply = value;
        }

    }

}
