//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 10:35:14 AM MDT 
//


package com.cognos.developer.schemas.bmt._60._7;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.developer.cognos.com/schemas/bmt/60/7}objectType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;group ref="{http://www.developer.cognos.com/schemas/bmt/60/7}levelBaseHierarchy"/>
 *           &lt;group ref="{http://www.developer.cognos.com/schemas/bmt/60/7}parentChildHierarchy" maxOccurs="unbounded"/>
 *         &lt;/choice>
 *         &lt;group ref="{http://www.developer.cognos.com/schemas/bmt/60/7}hierarchyProperties"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "level",
    "parentChildHierarchy",
    "externalName",
    "multiRoot",
    "balanced",
    "ragged",
    "rootMember",
    "rootMUN",
    "rootCaption",
    "sortedHierarchy",
    "cardinality",
    "parentChild",
    "externalNumberOfLevels",
    "isWideFan"
})
@XmlRootElement(name = "hierarchy")
public class Hierarchy
    extends com.cognos.developer.schemas.bmt._60._7.ObjectType
{

    protected List<com.cognos.developer.schemas.bmt._60._7.Level> level;
    @XmlElements({
        @XmlElement(name = "queryItem", type = com.cognos.developer.schemas.bmt._60._7.QueryItem.class),
        @XmlElement(name = "queryItemFolder", type = com.cognos.developer.schemas.bmt._60._7.QueryItemFolderType.class)
    })
    protected List<com.cognos.developer.schemas.bmt._60._7.ReportObjectType> parentChildHierarchy;
    protected String externalName;
    @XmlElement(defaultValue = "false")
    protected Boolean multiRoot;
    @XmlElement(defaultValue = "true")
    protected Boolean balanced;
    @XmlElement(defaultValue = "false")
    protected Boolean ragged;
    protected String rootMember;
    protected String rootMUN;
    protected List<com.cognos.developer.schemas.bmt._60._7.NameType> rootCaption;
    @XmlElement(defaultValue = "none")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String sortedHierarchy;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger cardinality;
    @XmlElement(defaultValue = "false")
    protected Boolean parentChild;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger externalNumberOfLevels;
    @XmlElement(defaultValue = "false")
    protected Boolean isWideFan;

    /**
     * Gets the value of the level property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the level property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLevel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link com.cognos.developer.schemas.bmt._60._7.Level }
     * 
     * 
     */
    public List<com.cognos.developer.schemas.bmt._60._7.Level> getLevel() {
        if (level == null) {
            level = new ArrayList<com.cognos.developer.schemas.bmt._60._7.Level>();
        }
        return this.level;
    }

    /**
     * Gets the value of the parentChildHierarchy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the parentChildHierarchy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParentChildHierarchy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link com.cognos.developer.schemas.bmt._60._7.QueryItem }
     * {@link com.cognos.developer.schemas.bmt._60._7.QueryItemFolderType }
     * 
     * 
     */
    public List<com.cognos.developer.schemas.bmt._60._7.ReportObjectType> getParentChildHierarchy() {
        if (parentChildHierarchy == null) {
            parentChildHierarchy = new ArrayList<com.cognos.developer.schemas.bmt._60._7.ReportObjectType>();
        }
        return this.parentChildHierarchy;
    }

    /**
     * Gets the value of the externalName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalName() {
        return externalName;
    }

    /**
     * Sets the value of the externalName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalName(String value) {
        this.externalName = value;
    }

    /**
     * Gets the value of the multiRoot property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMultiRoot() {
        return multiRoot;
    }

    /**
     * Sets the value of the multiRoot property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMultiRoot(Boolean value) {
        this.multiRoot = value;
    }

    /**
     * Gets the value of the balanced property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBalanced() {
        return balanced;
    }

    /**
     * Sets the value of the balanced property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBalanced(Boolean value) {
        this.balanced = value;
    }

    /**
     * Gets the value of the ragged property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRagged() {
        return ragged;
    }

    /**
     * Sets the value of the ragged property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRagged(Boolean value) {
        this.ragged = value;
    }

    /**
     * Gets the value of the rootMember property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRootMember() {
        return rootMember;
    }

    /**
     * Sets the value of the rootMember property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRootMember(String value) {
        this.rootMember = value;
    }

    /**
     * Gets the value of the rootMUN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRootMUN() {
        return rootMUN;
    }

    /**
     * Sets the value of the rootMUN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRootMUN(String value) {
        this.rootMUN = value;
    }

    /**
     * Gets the value of the rootCaption property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rootCaption property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRootCaption().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link com.cognos.developer.schemas.bmt._60._7.NameType }
     * 
     * 
     */
    public List<com.cognos.developer.schemas.bmt._60._7.NameType> getRootCaption() {
        if (rootCaption == null) {
            rootCaption = new ArrayList<com.cognos.developer.schemas.bmt._60._7.NameType>();
        }
        return this.rootCaption;
    }

    /**
     * Gets the value of the sortedHierarchy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSortedHierarchy() {
        return sortedHierarchy;
    }

    /**
     * Sets the value of the sortedHierarchy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSortedHierarchy(String value) {
        this.sortedHierarchy = value;
    }

    /**
     * Gets the value of the cardinality property.
     * 
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getCardinality() {
        return cardinality;
    }

    /**
     * Sets the value of the cardinality property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setCardinality(BigInteger value) {
        this.cardinality = value;
    }

    /**
     * Gets the value of the parentChild property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isParentChild() {
        return parentChild;
    }

    /**
     * Sets the value of the parentChild property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setParentChild(Boolean value) {
        this.parentChild = value;
    }

    /**
     * Gets the value of the externalNumberOfLevels property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getExternalNumberOfLevels() {
        return externalNumberOfLevels;
    }

    /**
     * Sets the value of the externalNumberOfLevels property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *     
     */
    public void setExternalNumberOfLevels(BigInteger value) {
        this.externalNumberOfLevels = value;
    }

    /**
     * Gets the value of the isWideFan property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsWideFan() {
        return isWideFan;
    }

    /**
     * Sets the value of the isWideFan property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsWideFan(Boolean value) {
        this.isWideFan = value;
    }

}
