//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 10:35:14 AM MDT 
//


package com.cognos.developer.schemas.bmt._60._7;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.developer.cognos.com/schemas/bmt/60/7}queryItemFolderType">
 *       &lt;sequence>
 *         &lt;element name="isUnique" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="externalName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="externalOrdinal" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="isManual" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="memberSort" type="{http://www.developer.cognos.com/schemas/bmt/60/7}orderByType" minOccurs="0"/>
 *         &lt;element name="orderOfMagnitude" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "isUnique",
    "externalName",
    "externalOrdinal",
    "isManual",
    "memberSort",
    "orderOfMagnitude"
})
@XmlRootElement(name = "level")
public class Level
    extends QueryItemFolderType
{

    @XmlElement(defaultValue = "false")
    protected Boolean isUnique;
    protected String externalName;
    protected BigInteger externalOrdinal;
    protected Boolean isManual;
    protected com.cognos.developer.schemas.bmt._60._7.OrderByType memberSort;
    @XmlElement(defaultValue = "0")
    protected BigInteger orderOfMagnitude;

    /**
     * Gets the value of the isUnique property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsUnique() {
        return isUnique;
    }

    /**
     * Sets the value of the isUnique property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsUnique(Boolean value) {
        this.isUnique = value;
    }

    /**
     * Gets the value of the externalName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalName() {
        return externalName;
    }

    /**
     * Sets the value of the externalName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalName(String value) {
        this.externalName = value;
    }

    /**
     * Gets the value of the externalOrdinal property.
     * 
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getExternalOrdinal() {
        return externalOrdinal;
    }

    /**
     * Sets the value of the externalOrdinal property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setExternalOrdinal(BigInteger value) {
        this.externalOrdinal = value;
    }

    /**
     * Gets the value of the isManual property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isIsManual() {
        return isManual;
    }

    /**
     * Sets the value of the isManual property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setIsManual(Boolean value) {
        this.isManual = value;
    }

    /**
     * Gets the value of the memberSort property.
     *
     * @return
     *     possible object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.OrderByType }
     *
     */
    public com.cognos.developer.schemas.bmt._60._7.OrderByType getMemberSort() {
        return memberSort;
    }

    /**
     * Sets the value of the memberSort property.
     *
     * @param value
     *     allowed object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.OrderByType }
     *
     */
    public void setMemberSort(com.cognos.developer.schemas.bmt._60._7.OrderByType value) {
        this.memberSort = value;
    }

    /**
     * Gets the value of the orderOfMagnitude property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getOrderOfMagnitude() {
        return orderOfMagnitude;
    }

    /**
     * Sets the value of the orderOfMagnitude property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *     
     */
    public void setOrderOfMagnitude(BigInteger value) {
        this.orderOfMagnitude = value;
    }

}
