//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 10:35:14 AM MDT 
//


package com.cognos.developer.schemas.bmt._60._7;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.developer.cognos.com/schemas/bmt/60/7}queryItemType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.developer.cognos.com/schemas/bmt/60/7}measure" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="isHierarchical" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="aggregateRules" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="aggregateRule" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="dimensionRef" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                             &lt;element name="applyAggregate">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *                                   &lt;enumeration value="unsupported"/>
 *                                   &lt;enumeration value="unknown"/>
 *                                   &lt;enumeration value="sum"/>
 *                                   &lt;enumeration value="minimum"/>
 *                                   &lt;enumeration value="maximum"/>
 *                                   &lt;enumeration value="average"/>
 *                                   &lt;enumeration value="count"/>
 *                                   &lt;enumeration value="firstPeriod"/>
 *                                   &lt;enumeration value="lastPeriod"/>
 *                                   &lt;enumeration value="standardDeviation"/>
 *                                   &lt;enumeration value="variance"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="allocationRule" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *               &lt;enumeration value="default"/>
 *               &lt;enumeration value="constant"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "measure",
    "isHierarchical",
    "aggregateRules",
    "allocationRule"
})
@XmlRootElement(name = "measure")
public class Measure
    extends com.cognos.developer.schemas.bmt._60._7.QueryItemType
{

    protected List<com.cognos.developer.schemas.bmt._60._7.Measure> measure;
    @XmlElement(defaultValue = "false")
    protected Boolean isHierarchical;
    protected com.cognos.developer.schemas.bmt._60._7.Measure.AggregateRules aggregateRules;
    @XmlElement(defaultValue = "default")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String allocationRule;

    /**
     * Gets the value of the measure property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the measure property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMeasure().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link com.cognos.developer.schemas.bmt._60._7.Measure }
     *
     *
     */
    public List<com.cognos.developer.schemas.bmt._60._7.Measure> getMeasure() {
        if (measure == null) {
            measure = new ArrayList<com.cognos.developer.schemas.bmt._60._7.Measure>();
        }
        return this.measure;
    }

    /**
     * Gets the value of the isHierarchical property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isIsHierarchical() {
        return isHierarchical;
    }

    /**
     * Sets the value of the isHierarchical property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setIsHierarchical(Boolean value) {
        this.isHierarchical = value;
    }

    /**
     * Gets the value of the aggregateRules property.
     *
     * @return
     *     possible object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.Measure.AggregateRules }
     *
     */
    public com.cognos.developer.schemas.bmt._60._7.Measure.AggregateRules getAggregateRules() {
        return aggregateRules;
    }

    /**
     * Sets the value of the aggregateRules property.
     *
     * @param value
     *     allowed object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.Measure.AggregateRules }
     *
     */
    public void setAggregateRules(com.cognos.developer.schemas.bmt._60._7.Measure.AggregateRules value) {
        this.aggregateRules = value;
    }

    /**
     * Gets the value of the allocationRule property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAllocationRule() {
        return allocationRule;
    }

    /**
     * Sets the value of the allocationRule property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAllocationRule(String value) {
        this.allocationRule = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="aggregateRule" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="dimensionRef" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                   &lt;element name="applyAggregate">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
     *                         &lt;enumeration value="unsupported"/>
     *                         &lt;enumeration value="unknown"/>
     *                         &lt;enumeration value="sum"/>
     *                         &lt;enumeration value="minimum"/>
     *                         &lt;enumeration value="maximum"/>
     *                         &lt;enumeration value="average"/>
     *                         &lt;enumeration value="count"/>
     *                         &lt;enumeration value="firstPeriod"/>
     *                         &lt;enumeration value="lastPeriod"/>
     *                         &lt;enumeration value="standardDeviation"/>
     *                         &lt;enumeration value="variance"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "aggregateRule"
    })
    public static class AggregateRules {

        protected List<com.cognos.developer.schemas.bmt._60._7.Measure.AggregateRules.AggregateRule> aggregateRule;

        /**
         * Gets the value of the aggregateRule property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the aggregateRule property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAggregateRule().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link com.cognos.developer.schemas.bmt._60._7.Measure.AggregateRules.AggregateRule }
         *
         *
         */
        public List<com.cognos.developer.schemas.bmt._60._7.Measure.AggregateRules.AggregateRule> getAggregateRule() {
            if (aggregateRule == null) {
                aggregateRule = new ArrayList<com.cognos.developer.schemas.bmt._60._7.Measure.AggregateRules.AggregateRule>();
            }
            return this.aggregateRule;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="dimensionRef" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *         &lt;element name="applyAggregate">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
         *               &lt;enumeration value="unsupported"/>
         *               &lt;enumeration value="unknown"/>
         *               &lt;enumeration value="sum"/>
         *               &lt;enumeration value="minimum"/>
         *               &lt;enumeration value="maximum"/>
         *               &lt;enumeration value="average"/>
         *               &lt;enumeration value="count"/>
         *               &lt;enumeration value="firstPeriod"/>
         *               &lt;enumeration value="lastPeriod"/>
         *               &lt;enumeration value="standardDeviation"/>
         *               &lt;enumeration value="variance"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "dimensionRef",
            "applyAggregate"
        })
        public static class AggregateRule {

            @XmlElement(required = true)
            protected Object dimensionRef;
            @XmlElement(required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            protected String applyAggregate;

            /**
             * Gets the value of the dimensionRef property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getDimensionRef() {
                return dimensionRef;
            }

            /**
             * Sets the value of the dimensionRef property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setDimensionRef(Object value) {
                this.dimensionRef = value;
            }

            /**
             * Gets the value of the applyAggregate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getApplyAggregate() {
                return applyAggregate;
            }

            /**
             * Sets the value of the applyAggregate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setApplyAggregate(String value) {
                this.applyAggregate = value;
            }

        }

    }

}
