//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 10:35:14 AM MDT 
//


package com.cognos.developer.schemas.bmt._60._7;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;para xmlns:bmtcr1="http://www.developer.cognos.com/schemas/bmt/60/7" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Objects that are not visible in IBM Cognos 10. Properties are typically not localizable.&lt;/para&gt;
 * </pre>
 * 
 * 			
 * 
 * <p>Java class for modelObjectType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="modelObjectType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{http://www.developer.cognos.com/schemas/bmt/60/7}guid" minOccurs="0"/>
 *         &lt;element ref="{http://www.developer.cognos.com/schemas/bmt/60/7}property" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "modelObjectType", propOrder = {
    "name",
    "guid",
    "property"
})
@XmlSeeAlso({
    RelationshipShortcutType.class,
    DataSourceType.class,
    RelationshipType.class,
    com.cognos.developer.schemas.bmt._60._7.ScopeRelationshipType.class,
    ParameterMapType.class,
    SecurityViewType.class,
    com.cognos.developer.schemas.bmt._60._7.Project.class
})
public class ModelObjectType {

    @XmlElement(required = true)
    protected String name;
    protected Object guid;
    protected List<com.cognos.developer.schemas.bmt._60._7.Property> property;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the guid property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getGuid() {
        return guid;
    }

    /**
     * Sets the value of the guid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setGuid(Object value) {
        this.guid = value;
    }

    /**
     * Gets the value of the property property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the property property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link com.cognos.developer.schemas.bmt._60._7.Property }
     * 
     * 
     */
    public List<com.cognos.developer.schemas.bmt._60._7.Property> getProperty() {
        if (property == null) {
            property = new ArrayList<com.cognos.developer.schemas.bmt._60._7.Property>();
        }
        return this.property;
    }

}
