//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 10:35:14 AM MDT 
//


package com.cognos.developer.schemas.bmt._60._7;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.cognos.developer.schemas.bmt._60._60 package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Folder_QNAME = new QName("http://www.developer.cognos.com/schemas/bmt/60/7", "folder");
    private final static QName _Guid_QNAME = new QName("http://www.developer.cognos.com/schemas/bmt/60/7", "guid");
    private final static QName _Relationship_QNAME = new QName("http://www.developer.cognos.com/schemas/bmt/60/7", "relationship");
    private final static QName _Sql_QNAME = new QName("http://www.developer.cognos.com/schemas/bmt/60/7", "sql");
    private final static QName _ScopeRelationship_QNAME = new QName("http://www.developer.cognos.com/schemas/bmt/60/7", "scopeRelationship");
    private final static QName _Datatype_QNAME = new QName("http://www.developer.cognos.com/schemas/bmt/60/7", "datatype");
    private final static QName _QueryItemFolder_QNAME = new QName("http://www.developer.cognos.com/schemas/bmt/60/7", "queryItemFolder");
    private final static QName _GenerateSQL_QNAME = new QName("http://www.developer.cognos.com/schemas/bmt/60/7", "generateSQL");
    private final static QName _SecurityObject_QNAME = new QName("http://www.developer.cognos.com/schemas/bmt/60/7", "securityObject");
    private final static QName _Filter_QNAME = new QName("http://www.developer.cognos.com/schemas/bmt/60/7", "filter");
    private final static QName _Viewref_QNAME = new QName("http://www.developer.cognos.com/schemas/bmt/60/7", "viewref");
    private final static QName _UpdateSubject_QNAME = new QName("http://www.developer.cognos.com/schemas/bmt/60/7", "updateSubject");
    private final static QName _DataSourceRef_QNAME = new QName("http://www.developer.cognos.com/schemas/bmt/60/7", "dataSourceRef");
    private final static QName _SecurityView_QNAME = new QName("http://www.developer.cognos.com/schemas/bmt/60/7", "securityView");
    private final static QName _DecisionRole_QNAME = new QName("http://www.developer.cognos.com/schemas/bmt/60/7", "decisionRole");
    private final static QName _Calculation_QNAME = new QName("http://www.developer.cognos.com/schemas/bmt/60/7", "calculation");
    private final static QName _ParameterMap_QNAME = new QName("http://www.developer.cognos.com/schemas/bmt/60/7", "parameterMap");
    private final static QName _CmSearchPath_QNAME = new QName("http://www.developer.cognos.com/schemas/bmt/60/7", "cmSearchPath");
    private final static QName _RelationshipShortcut_QNAME = new QName("http://www.developer.cognos.com/schemas/bmt/60/7", "relationshipShortcut");
    private final static QName _Expression_QNAME = new QName("http://www.developer.cognos.com/schemas/bmt/60/7", "expression");
    private final static QName _Steward_QNAME = new QName("http://www.developer.cognos.com/schemas/bmt/60/7", "steward");
    private final static QName _DataSource_QNAME = new QName("http://www.developer.cognos.com/schemas/bmt/60/7", "dataSource");
    private final static QName _Package_QNAME = new QName("http://www.developer.cognos.com/schemas/bmt/60/7", "package");
    private final static QName _AliasTableMapRef_QNAME = new QName("http://www.developer.cognos.com/schemas/bmt/60/7", "aliasTableMapRef");
    private final static QName _Object_QNAME = new QName("http://www.developer.cognos.com/schemas/bmt/60/7", "object");
    private final static QName _Shortcut_QNAME = new QName("http://www.developer.cognos.com/schemas/bmt/60/7", "shortcut");
    private final static QName _Function_QNAME = new QName("http://www.developer.cognos.com/schemas/bmt/60/7", "function");
    private final static QName _RefobjViaShortcutRefobj_QNAME = new QName("http://www.developer.cognos.com/schemas/bmt/60/7", "refobj");
    private final static QName _SqlTypeColumn_QNAME = new QName("http://www.developer.cognos.com/schemas/bmt/60/7", "column");
    private final static QName _SqlTypeTable_QNAME = new QName("http://www.developer.cognos.com/schemas/bmt/60/7", "table");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.cognos.developer.schemas.bmt._60._60
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link QueryItemType }
     * 
     */
    public QueryItemType createQueryItemType() {
        return new QueryItemType();
    }

    /**
     * Create an instance of {@link Measure }
     * 
     */
    public Measure createMeasure() {
        return new Measure();
    }

    /**
     * Create an instance of {@link QuerySubjectType }
     * 
     */
    public QuerySubjectType createQuerySubjectType() {
        return new QuerySubjectType();
    }

    /**
     * Create an instance of {@link com.cognos.developer.schemas.bmt._60._7.QuerySubject }
     * 
     */
    public com.cognos.developer.schemas.bmt._60._7.QuerySubject createQuerySubject() {
        return new com.cognos.developer.schemas.bmt._60._7.QuerySubject();
    }

    /**
     * Create an instance of {@link Namespace }
     * 
     */
    public Namespace createNamespace() {
        return new Namespace();
    }

    /**
     * Create an instance of {@link FunctionSets }
     * 
     */
    public FunctionSets createFunctionSets() {
        return new FunctionSets();
    }

    /**
     * Create an instance of {@link QosOverrides }
     * 
     */
    public QosOverrides createQosOverrides() {
        return new QosOverrides();
    }

    /**
     * Create an instance of {@link Project }
     * 
     */
    public Project createProject() {
        return new Project();
    }

    /**
     * Create an instance of {@link Filters }
     * 
     */
    public Filters createFilters() {
        return new Filters();
    }

    /**
     * Create an instance of {@link DeterminantType2 }
     * 
     */
    public DeterminantType2 createDeterminantType2() {
        return new DeterminantType2();
    }

    /**
     * Create an instance of {@link StoredProcedureType }
     * 
     */
    public StoredProcedureType createStoredProcedureType() {
        return new StoredProcedureType();
    }

    /**
     * Create an instance of {@link StoredProcedureType.ProcParameters }
     * 
     */
    public StoredProcedureType.ProcParameters createStoredProcedureTypeProcParameters() {
        return new StoredProcedureType.ProcParameters();
    }

    /**
     * Create an instance of {@link SecurityFilterDefinitionType }
     * 
     */
    public SecurityFilterDefinitionType createSecurityFilterDefinitionType() {
        return new SecurityFilterDefinitionType();
    }

    /**
     * Create an instance of {@link com.cognos.developer.schemas.bmt._60._7.SecurityObjectType }
     * 
     */
    public com.cognos.developer.schemas.bmt._60._7.SecurityObjectType createSecurityObjectType() {
        return new com.cognos.developer.schemas.bmt._60._7.SecurityObjectType();
    }

    /**
     * Create an instance of {@link Project.PhysicalSources }
     * 
     */
    public Project.PhysicalSources createProjectPhysicalSources() {
        return new Project.PhysicalSources();
    }

    /**
     * Create an instance of {@link SupportedLocalesType }
     * 
     */
    public SupportedLocalesType createSupportedLocalesType() {
        return new SupportedLocalesType();
    }

    /**
     * Create an instance of {@link SecurityViewType }
     * 
     */
    public SecurityViewType createSecurityViewType() {
        return new SecurityViewType();
    }

    /**
     * Create an instance of {@link Namespace.LinkedNode }
     * 
     */
    public Namespace.LinkedNode createNamespaceLinkedNode() {
        return new Namespace.LinkedNode();
    }

    /**
     * Create an instance of {@link Namespace.LinkedNode.Source }
     * 
     */
    public Namespace.LinkedNode.Source createNamespaceLinkedNodeSource() {
        return new Namespace.LinkedNode.Source();
    }

    /**
     * Create an instance of {@link ScopeRelationshipType }
     * 
     */
    public ScopeRelationshipType createScopeRelationshipType() {
        return new ScopeRelationshipType();
    }

    /**
     * Create an instance of {@link ScopeRelationshipType.Scope }
     * 
     */
    public ScopeRelationshipType.Scope createScopeRelationshipTypeScope() {
        return new ScopeRelationshipType.Scope();
    }

    /**
     * Create an instance of {@link com.cognos.developer.schemas.bmt._60._7.OrderByType }
     * 
     */
    public com.cognos.developer.schemas.bmt._60._7.OrderByType createOrderByType() {
        return new com.cognos.developer.schemas.bmt._60._7.OrderByType();
    }

    /**
     * Create an instance of {@link CalculationType }
     * 
     */
    public CalculationType createCalculationType() {
        return new CalculationType();
    }

    /**
     * Create an instance of {@link QuerySubjectType.PreviewFilters }
     * 
     */
    public QuerySubjectType.PreviewFilters createQuerySubjectTypePreviewFilters() {
        return new QuerySubjectType.PreviewFilters();
    }

    /**
     * Create an instance of {@link com.cognos.developer.schemas.bmt._60._7.DefinitionType }
     * 
     */
    public com.cognos.developer.schemas.bmt._60._7.DefinitionType createDefinitionType() {
        return new com.cognos.developer.schemas.bmt._60._7.DefinitionType();
    }

    /**
     * Create an instance of {@link com.cognos.developer.schemas.bmt._60._7.DefinitionType.QueryOperation }
     * 
     */
    public com.cognos.developer.schemas.bmt._60._7.DefinitionType.QueryOperation createDefinitionTypeQueryOperation() {
        return new com.cognos.developer.schemas.bmt._60._7.DefinitionType.QueryOperation();
    }

    /**
     * Create an instance of {@link com.cognos.developer.schemas.bmt._60._7.DefinitionType.ModelQuery }
     * 
     */
    public com.cognos.developer.schemas.bmt._60._7.DefinitionType.ModelQuery createDefinitionTypeModelQuery() {
        return new com.cognos.developer.schemas.bmt._60._7.DefinitionType.ModelQuery();
    }

    /**
     * Create an instance of {@link com.cognos.developer.schemas.bmt._60._7.DefinitionType.ModelQuery.Relationships }
     * 
     */
    public com.cognos.developer.schemas.bmt._60._7.DefinitionType.ModelQuery.Relationships createDefinitionTypeModelQueryRelationships() {
        return new com.cognos.developer.schemas.bmt._60._7.DefinitionType.ModelQuery.Relationships();
    }

    /**
     * Create an instance of {@link com.cognos.developer.schemas.bmt._60._7.DefinitionType.ModelQuery.Relationships.RelationshipDefinition }
     * 
     */
    public com.cognos.developer.schemas.bmt._60._7.DefinitionType.ModelQuery.Relationships.RelationshipDefinition createDefinitionTypeModelQueryRelationshipsRelationshipDefinition() {
        return new com.cognos.developer.schemas.bmt._60._7.DefinitionType.ModelQuery.Relationships.RelationshipDefinition();
    }

    /**
     * Create an instance of {@link com.cognos.developer.schemas.bmt._60._7.DefinitionType.DbQuery }
     * 
     */
    public com.cognos.developer.schemas.bmt._60._7.DefinitionType.DbQuery createDefinitionTypeDbQuery() {
        return new com.cognos.developer.schemas.bmt._60._7.DefinitionType.DbQuery();
    }

    /**
     * Create an instance of {@link FunctionType }
     * 
     */
    public FunctionType createFunctionType() {
        return new FunctionType();
    }

    /**
     * Create an instance of {@link FunctionType.ProcParameters }
     * 
     */
    public FunctionType.ProcParameters createFunctionTypeProcParameters() {
        return new FunctionType.ProcParameters();
    }

    /**
     * Create an instance of {@link PackageViewType }
     * 
     */
    public PackageViewType createPackageViewType() {
        return new PackageViewType();
    }

    /**
     * Create an instance of {@link Measure.AggregateRules }
     * 
     */
    public Measure.AggregateRules createMeasureAggregateRules() {
        return new Measure.AggregateRules();
    }

    /**
     * Create an instance of {@link QueryItemType.Roles }
     * 
     */
    public QueryItemType.Roles createQueryItemTypeRoles() {
        return new QueryItemType.Roles();
    }

    /**
     * Create an instance of {@link DataSourceType }
     * 
     */
    public DataSourceType createDataSourceType() {
        return new DataSourceType();
    }

    /**
     * Create an instance of {@link RelationshipShortcutType }
     * 
     */
    public RelationshipShortcutType createRelationshipShortcutType() {
        return new RelationshipShortcutType();
    }

    /**
     * Create an instance of {@link com.cognos.developer.schemas.bmt._60._7.ExpressionType }
     * 
     */
    public com.cognos.developer.schemas.bmt._60._7.ExpressionType createExpressionType() {
        return new com.cognos.developer.schemas.bmt._60._7.ExpressionType();
    }

    /**
     * Create an instance of {@link ReportObjectType }
     * 
     */
    public ReportObjectType createReportObjectType() {
        return new ReportObjectType();
    }

    /**
     * Create an instance of {@link NameType }
     * 
     */
    public NameType createNameType() {
        return new NameType();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link PropertyType }
     * 
     */
    public PropertyType createPropertyType() {
        return new PropertyType();
    }

    /**
     * Create an instance of {@link PromptInfoType }
     * 
     */
    public PromptInfoType createPromptInfoType() {
        return new PromptInfoType();
    }

    /**
     * Create an instance of {@link QueryItem }
     * 
     */
    public QueryItem createQueryItem() {
        return new QueryItem();
    }

    /**
     * Create an instance of {@link ObjectType }
     * 
     */
    public ObjectType createObjectType() {
        return new ObjectType();
    }

    /**
     * Create an instance of {@link MeasureFolder }
     * 
     */
    public MeasureFolder createMeasureFolder() {
        return new MeasureFolder();
    }

    /**
     * Create an instance of {@link NamespaceType }
     * 
     */
    public NamespaceType createNamespaceType() {
        return new NamespaceType();
    }

    /**
     * Create an instance of {@link SectionType }
     * 
     */
    public SectionType createSectionType() {
        return new SectionType();
    }

    /**
     * Create an instance of {@link ShortcutType }
     * 
     */
    public ShortcutType createShortcutType() {
        return new ShortcutType();
    }

    /**
     * Create an instance of {@link QuerySubjectType.Levels }
     * 
     */
    public QuerySubjectType.Levels createQuerySubjectTypeLevels() {
        return new QuerySubjectType.Levels();
    }

    /**
     * Create an instance of {@link QuerySubjectType.Hierarchies }
     * 
     */
    public QuerySubjectType.Hierarchies createQuerySubjectTypeHierarchies() {
        return new QuerySubjectType.Hierarchies();
    }

    /**
     * Create an instance of {@link QuerySubjectType.SecurityFilters }
     * 
     */
    public QuerySubjectType.SecurityFilters createQuerySubjectTypeSecurityFilters() {
        return new QuerySubjectType.SecurityFilters();
    }

    /**
     * Create an instance of {@link com.cognos.developer.schemas.bmt._60._7.QuerySubject.Determinants }
     * 
     */
    public com.cognos.developer.schemas.bmt._60._7.QuerySubject.Determinants createQuerySubjectDeterminants() {
        return new com.cognos.developer.schemas.bmt._60._7.QuerySubject.Determinants();
    }

    /**
     * Create an instance of {@link com.cognos.developer.schemas.bmt._60._7.QueryItemFolderType }
     * 
     */
    public com.cognos.developer.schemas.bmt._60._7.QueryItemFolderType createQueryItemFolderType() {
        return new com.cognos.developer.schemas.bmt._60._7.QueryItemFolderType();
    }

    /**
     * Create an instance of {@link RelationshipType }
     * 
     */
    public RelationshipType createRelationshipType() {
        return new RelationshipType();
    }

    /**
     * Create an instance of {@link FilterType }
     * 
     */
    public FilterType createFilterType() {
        return new FilterType();
    }

    /**
     * Create an instance of {@link Dimension }
     * 
     */
    public Dimension createDimension() {
        return new Dimension();
    }

    /**
     * Create an instance of {@link Hierarchy }
     * 
     */
    public Hierarchy createHierarchy() {
        return new Hierarchy();
    }

    /**
     * Create an instance of {@link com.cognos.developer.schemas.bmt._60._7.Level }
     * 
     */
    public com.cognos.developer.schemas.bmt._60._7.Level createLevel() {
        return new com.cognos.developer.schemas.bmt._60._7.Level();
    }

    /**
     * Create an instance of {@link HierarchyFolder }
     * 
     */
    public HierarchyFolder createHierarchyFolder() {
        return new HierarchyFolder();
    }

    /**
     * Create an instance of {@link ParameterMapType }
     * 
     */
    public ParameterMapType createParameterMapType() {
        return new ParameterMapType();
    }

    /**
     * Create an instance of {@link FunctionSets.FunctionSet }
     * 
     */
    public FunctionSets.FunctionSet createFunctionSetsFunctionSet() {
        return new FunctionSets.FunctionSet();
    }

    /**
     * Create an instance of {@link QosOverrides.QosOverride }
     * 
     */
    public QosOverrides.QosOverride createQosOverridesQosOverride() {
        return new QosOverrides.QosOverride();
    }

    /**
     * Create an instance of {@link RefobjViaShortcut }
     * 
     */
    public RefobjViaShortcut createRefobjViaShortcut() {
        return new RefobjViaShortcut();
    }

    /**
     * Create an instance of {@link com.cognos.developer.schemas.bmt._60._7.DecisionRoleType }
     * 
     */
    public com.cognos.developer.schemas.bmt._60._7.DecisionRoleType createDecisionRoleType() {
        return new com.cognos.developer.schemas.bmt._60._7.DecisionRoleType();
    }

    /**
     * Create an instance of {@link Mproperty }
     * 
     */
    public Mproperty createMproperty() {
        return new Mproperty();
    }

    /**
     * Create an instance of {@link ModelObjectType }
     * 
     */
    public ModelObjectType createModelObjectType() {
        return new ModelObjectType();
    }

    /**
     * Create an instance of {@link Project.DataSources }
     * 
     */
    public Project.DataSources createProjectDataSources() {
        return new Project.DataSources();
    }

    /**
     * Create an instance of {@link Project.ParameterMaps }
     * 
     */
    public Project.ParameterMaps createProjectParameterMaps() {
        return new Project.ParameterMaps();
    }

    /**
     * Create an instance of {@link Project.SecurityViews }
     * 
     */
    public Project.SecurityViews createProjectSecurityViews() {
        return new Project.SecurityViews();
    }

    /**
     * Create an instance of {@link Project.Packages }
     * 
     */
    public Project.Packages createProjectPackages() {
        return new Project.Packages();
    }

    /**
     * Create an instance of {@link SqlType }
     * 
     */
    public SqlType createSqlType() {
        return new SqlType();
    }

    /**
     * Create an instance of {@link Filters.FilterDefinition }
     * 
     */
    public Filters.FilterDefinition createFiltersFilterDefinition() {
        return new Filters.FilterDefinition();
    }

    /**
     * Create an instance of {@link HierarchyType }
     * 
     */
    public HierarchyType createHierarchyType() {
        return new HierarchyType();
    }

    /**
     * Create an instance of {@link ParameterMapEntryType }
     * 
     */
    public ParameterMapEntryType createParameterMapEntryType() {
        return new ParameterMapEntryType();
    }

    /**
     * Create an instance of {@link DeterminantType }
     * 
     */
    public DeterminantType createDeterminantType() {
        return new DeterminantType();
    }

    /**
     * Create an instance of {@link com.cognos.developer.schemas.bmt._60._7.QueryItemMapType }
     * 
     */
    public com.cognos.developer.schemas.bmt._60._7.QueryItemMapType createQueryItemMapType() {
        return new com.cognos.developer.schemas.bmt._60._7.QueryItemMapType();
    }

    /**
     * Create an instance of {@link MacroType }
     * 
     */
    public MacroType createMacroType() {
        return new MacroType();
    }

    /**
     * Create an instance of {@link DataSourceRefsType }
     * 
     */
    public DataSourceRefsType createDataSourceRefsType() {
        return new DataSourceRefsType();
    }

    /**
     * Create an instance of {@link KeyType }
     * 
     */
    public KeyType createKeyType() {
        return new KeyType();
    }

    /**
     * Create an instance of {@link CardinalityType }
     * 
     */
    public CardinalityType createCardinalityType() {
        return new CardinalityType();
    }

    /**
     * Create an instance of {@link RefCollectionType }
     * 
     */
    public RefCollectionType createRefCollectionType() {
        return new RefCollectionType();
    }

    /**
     * Create an instance of {@link SecurityDefinitionSetType }
     * 
     */
    public SecurityDefinitionSetType createSecurityDefinitionSetType() {
        return new SecurityDefinitionSetType();
    }

    /**
     * Create an instance of {@link DeterminantType2 .Key }
     * 
     */
    public DeterminantType2 .Key createDeterminantType2Key() {
        return new DeterminantType2 .Key();
    }

    /**
     * Create an instance of {@link StoredProcedureType.ProcParameters.ProcParameter }
     * 
     */
    public StoredProcedureType.ProcParameters.ProcParameter createStoredProcedureTypeProcParametersProcParameter() {
        return new StoredProcedureType.ProcParameters.ProcParameter();
    }

    /**
     * Create an instance of {@link SecurityFilterDefinitionType.BasedOn }
     * 
     */
    public SecurityFilterDefinitionType.BasedOn createSecurityFilterDefinitionTypeBasedOn() {
        return new SecurityFilterDefinitionType.BasedOn();
    }

    /**
     * Create an instance of {@link com.cognos.developer.schemas.bmt._60._7.SecurityObjectType.DisplayPath }
     * 
     */
    public com.cognos.developer.schemas.bmt._60._7.SecurityObjectType.DisplayPath createSecurityObjectTypeDisplayPath() {
        return new com.cognos.developer.schemas.bmt._60._7.SecurityObjectType.DisplayPath();
    }

    /**
     * Create an instance of {@link Project.PhysicalSources.PhysicalSource }
     * 
     */
    public Project.PhysicalSources.PhysicalSource createProjectPhysicalSourcesPhysicalSource() {
        return new Project.PhysicalSources.PhysicalSource();
    }

    /**
     * Create an instance of {@link SupportedLocalesType.Locale }
     * 
     */
    public SupportedLocalesType.Locale createSupportedLocalesTypeLocale() {
        return new SupportedLocalesType.Locale();
    }

    /**
     * Create an instance of {@link SecurityViewType.Definition }
     * 
     */
    public SecurityViewType.Definition createSecurityViewTypeDefinition() {
        return new SecurityViewType.Definition();
    }

    /**
     * Create an instance of {@link SecurityViewType.Access }
     * 
     */
    public SecurityViewType.Access createSecurityViewTypeAccess() {
        return new SecurityViewType.Access();
    }

    /**
     * Create an instance of {@link Namespace.LinkedNode.QueryPath }
     * 
     */
    public Namespace.LinkedNode.QueryPath createNamespaceLinkedNodeQueryPath() {
        return new Namespace.LinkedNode.QueryPath();
    }

    /**
     * Create an instance of {@link Namespace.LinkedNode.Source.Connection }
     * 
     */
    public Namespace.LinkedNode.Source.Connection createNamespaceLinkedNodeSourceConnection() {
        return new Namespace.LinkedNode.Source.Connection();
    }

    /**
     * Create an instance of {@link Namespace.LinkedNode.Source.Scope }
     * 
     */
    public Namespace.LinkedNode.Source.Scope createNamespaceLinkedNodeSourceScope() {
        return new Namespace.LinkedNode.Source.Scope();
    }

    /**
     * Create an instance of {@link Namespace.LinkedNode.Source.Signon }
     * 
     */
    public Namespace.LinkedNode.Source.Signon createNamespaceLinkedNodeSourceSignon() {
        return new Namespace.LinkedNode.Source.Signon();
    }

    /**
     * Create an instance of {@link ScopeRelationshipType.Scope.MeasureScope }
     * 
     */
    public ScopeRelationshipType.Scope.MeasureScope createScopeRelationshipTypeScopeMeasureScope() {
        return new ScopeRelationshipType.Scope.MeasureScope();
    }

    /**
     * Create an instance of {@link com.cognos.developer.schemas.bmt._60._7.OrderByType.SortItem }
     * 
     */
    public com.cognos.developer.schemas.bmt._60._7.OrderByType.SortItem createOrderByTypeSortItem() {
        return new com.cognos.developer.schemas.bmt._60._7.OrderByType.SortItem();
    }

    /**
     * Create an instance of {@link CalculationType.Hierarchies }
     * 
     */
    public CalculationType.Hierarchies createCalculationTypeHierarchies() {
        return new CalculationType.Hierarchies();
    }

    /**
     * Create an instance of {@link CalculationType.Dimensions }
     * 
     */
    public CalculationType.Dimensions createCalculationTypeDimensions() {
        return new CalculationType.Dimensions();
    }

    /**
     * Create an instance of {@link CalculationType.Datasources }
     * 
     */
    public CalculationType.Datasources createCalculationTypeDatasources() {
        return new CalculationType.Datasources();
    }

    /**
     * Create an instance of {@link QuerySubjectType.PreviewFilters.PreviewFilter }
     * 
     */
    public QuerySubjectType.PreviewFilters.PreviewFilter createQuerySubjectTypePreviewFiltersPreviewFilter() {
        return new QuerySubjectType.PreviewFilters.PreviewFilter();
    }

    /**
     * Create an instance of {@link com.cognos.developer.schemas.bmt._60._7.DefinitionType.MdQuery }
     * 
     */
    public com.cognos.developer.schemas.bmt._60._7.DefinitionType.MdQuery createDefinitionTypeMdQuery() {
        return new com.cognos.developer.schemas.bmt._60._7.DefinitionType.MdQuery();
    }

    /**
     * Create an instance of {@link com.cognos.developer.schemas.bmt._60._7.DefinitionType.QueryOperation.QuerySubjectRefs }
     * 
     */
    public com.cognos.developer.schemas.bmt._60._7.DefinitionType.QueryOperation.QuerySubjectRefs createDefinitionTypeQueryOperationQuerySubjectRefs() {
        return new com.cognos.developer.schemas.bmt._60._7.DefinitionType.QueryOperation.QuerySubjectRefs();
    }

    /**
     * Create an instance of {@link com.cognos.developer.schemas.bmt._60._7.DefinitionType.ModelQuery.Relationships.RelationshipDefinition.EmbeddedRelationship }
     * 
     */
    public com.cognos.developer.schemas.bmt._60._7.DefinitionType.ModelQuery.Relationships.RelationshipDefinition.EmbeddedRelationship createDefinitionTypeModelQueryRelationshipsRelationshipDefinitionEmbeddedRelationship() {
        return new com.cognos.developer.schemas.bmt._60._7.DefinitionType.ModelQuery.Relationships.RelationshipDefinition.EmbeddedRelationship();
    }

    /**
     * Create an instance of {@link com.cognos.developer.schemas.bmt._60._7.DefinitionType.DbQuery.Index }
     * 
     */
    public com.cognos.developer.schemas.bmt._60._7.DefinitionType.DbQuery.Index createDefinitionTypeDbQueryIndex() {
        return new com.cognos.developer.schemas.bmt._60._7.DefinitionType.DbQuery.Index();
    }

    /**
     * Create an instance of {@link FunctionType.Result }
     * 
     */
    public FunctionType.Result createFunctionTypeResult() {
        return new FunctionType.Result();
    }

    /**
     * Create an instance of {@link FunctionType.ProcParameters.ProcParameter }
     * 
     */
    public FunctionType.ProcParameters.ProcParameter createFunctionTypeProcParametersProcParameter() {
        return new FunctionType.ProcParameters.ProcParameter();
    }

    /**
     * Create an instance of {@link PackageViewType.Definition }
     * 
     */
    public PackageViewType.Definition createPackageViewTypeDefinition() {
        return new PackageViewType.Definition();
    }

    /**
     * Create an instance of {@link PackageViewType.AdminAccess }
     * 
     */
    public PackageViewType.AdminAccess createPackageViewTypeAdminAccess() {
        return new PackageViewType.AdminAccess();
    }

    /**
     * Create an instance of {@link Measure.AggregateRules.AggregateRule }
     * 
     */
    public Measure.AggregateRules.AggregateRule createMeasureAggregateRulesAggregateRule() {
        return new Measure.AggregateRules.AggregateRule();
    }

    /**
     * Create an instance of {@link QueryItemType.Roles.Role }
     * 
     */
    public QueryItemType.Roles.Role createQueryItemTypeRolesRole() {
        return new QueryItemType.Roles.Role();
    }

    /**
     * Create an instance of {@link DataSourceType.Type }
     * 
     */
    public DataSourceType.Type createDataSourceTypeType() {
        return new DataSourceType.Type();
    }

    /**
     * Create an instance of {@link RelationshipShortcutType.Left }
     * 
     */
    public RelationshipShortcutType.Left createRelationshipShortcutTypeLeft() {
        return new RelationshipShortcutType.Left();
    }

    /**
     * Create an instance of {@link RelationshipShortcutType.Right }
     * 
     */
    public RelationshipShortcutType.Right createRelationshipShortcutTypeRight() {
        return new RelationshipShortcutType.Right();
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link SectionType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.developer.cognos.com/schemas/bmt/60/7", name = "folder")
    public JAXBElement<SectionType> createFolder(SectionType value) {
        return new JAXBElement<SectionType>(_Folder_QNAME, SectionType.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link Object }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.developer.cognos.com/schemas/bmt/60/7", name = "guid")
    public JAXBElement<Object> createGuid(Object value) {
        return new JAXBElement<Object>(_Guid_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link RelationshipType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.developer.cognos.com/schemas/bmt/60/7", name = "relationship")
    public JAXBElement<RelationshipType> createRelationship(RelationshipType value) {
        return new JAXBElement<RelationshipType>(_Relationship_QNAME, RelationshipType.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link SqlType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.developer.cognos.com/schemas/bmt/60/7", name = "sql")
    public JAXBElement<SqlType> createSql(SqlType value) {
        return new JAXBElement<SqlType>(_Sql_QNAME, SqlType.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link ScopeRelationshipType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.developer.cognos.com/schemas/bmt/60/7", name = "scopeRelationship")
    public JAXBElement<ScopeRelationshipType> createScopeRelationship(ScopeRelationshipType value) {
        return new JAXBElement<ScopeRelationshipType>(_ScopeRelationship_QNAME, ScopeRelationshipType.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.developer.cognos.com/schemas/bmt/60/7", name = "datatype", defaultValue = "unknown")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDatatype(String value) {
        return new JAXBElement<String>(_Datatype_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link com.cognos.developer.schemas.bmt._60._7.QueryItemFolderType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.developer.cognos.com/schemas/bmt/60/7", name = "queryItemFolder")
    public JAXBElement<com.cognos.developer.schemas.bmt._60._7.QueryItemFolderType> createQueryItemFolder(com.cognos.developer.schemas.bmt._60._7.QueryItemFolderType value) {
        return new JAXBElement<com.cognos.developer.schemas.bmt._60._7.QueryItemFolderType>(_QueryItemFolder_QNAME, com.cognos.developer.schemas.bmt._60._7.QueryItemFolderType.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.developer.cognos.com/schemas/bmt/60/7", name = "generateSQL", defaultValue = "minimized")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createGenerateSQL(String value) {
        return new JAXBElement<String>(_GenerateSQL_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link com.cognos.developer.schemas.bmt._60._7.SecurityObjectType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.developer.cognos.com/schemas/bmt/60/7", name = "securityObject")
    public JAXBElement<com.cognos.developer.schemas.bmt._60._7.SecurityObjectType> createSecurityObject(com.cognos.developer.schemas.bmt._60._7.SecurityObjectType value) {
        return new JAXBElement<com.cognos.developer.schemas.bmt._60._7.SecurityObjectType>(_SecurityObject_QNAME, com.cognos.developer.schemas.bmt._60._7.SecurityObjectType.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link FilterType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.developer.cognos.com/schemas/bmt/60/7", name = "filter")
    public JAXBElement<FilterType> createFilter(FilterType value) {
        return new JAXBElement<FilterType>(_Filter_QNAME, FilterType.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.developer.cognos.com/schemas/bmt/60/7", name = "viewref")
    public JAXBElement<String> createViewref(String value) {
        return new JAXBElement<String>(_Viewref_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link QuerySubjectType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.developer.cognos.com/schemas/bmt/60/7", name = "updateSubject")
    public JAXBElement<QuerySubjectType> createUpdateSubject(QuerySubjectType value) {
        return new JAXBElement<QuerySubjectType>(_UpdateSubject_QNAME, QuerySubjectType.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.developer.cognos.com/schemas/bmt/60/7", name = "dataSourceRef")
    public JAXBElement<String> createDataSourceRef(String value) {
        return new JAXBElement<String>(_DataSourceRef_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link SecurityViewType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.developer.cognos.com/schemas/bmt/60/7", name = "securityView")
    public JAXBElement<SecurityViewType> createSecurityView(SecurityViewType value) {
        return new JAXBElement<SecurityViewType>(_SecurityView_QNAME, SecurityViewType.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link com.cognos.developer.schemas.bmt._60._7.DecisionRoleType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.developer.cognos.com/schemas/bmt/60/7", name = "decisionRole")
    public JAXBElement<com.cognos.developer.schemas.bmt._60._7.DecisionRoleType> createDecisionRole(com.cognos.developer.schemas.bmt._60._7.DecisionRoleType value) {
        return new JAXBElement<com.cognos.developer.schemas.bmt._60._7.DecisionRoleType>(_DecisionRole_QNAME, com.cognos.developer.schemas.bmt._60._7.DecisionRoleType.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link CalculationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.developer.cognos.com/schemas/bmt/60/7", name = "calculation")
    public JAXBElement<CalculationType> createCalculation(CalculationType value) {
        return new JAXBElement<CalculationType>(_Calculation_QNAME, CalculationType.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link ParameterMapType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.developer.cognos.com/schemas/bmt/60/7", name = "parameterMap")
    public JAXBElement<ParameterMapType> createParameterMap(ParameterMapType value) {
        return new JAXBElement<ParameterMapType>(_ParameterMap_QNAME, ParameterMapType.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.developer.cognos.com/schemas/bmt/60/7", name = "cmSearchPath")
    public JAXBElement<String> createCmSearchPath(String value) {
        return new JAXBElement<String>(_CmSearchPath_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link RelationshipShortcutType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.developer.cognos.com/schemas/bmt/60/7", name = "relationshipShortcut")
    public JAXBElement<RelationshipShortcutType> createRelationshipShortcut(RelationshipShortcutType value) {
        return new JAXBElement<RelationshipShortcutType>(_RelationshipShortcut_QNAME, RelationshipShortcutType.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link com.cognos.developer.schemas.bmt._60._7.ExpressionType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.developer.cognos.com/schemas/bmt/60/7", name = "expression")
    public JAXBElement<com.cognos.developer.schemas.bmt._60._7.ExpressionType> createExpression(com.cognos.developer.schemas.bmt._60._7.ExpressionType value) {
        return new JAXBElement<com.cognos.developer.schemas.bmt._60._7.ExpressionType>(_Expression_QNAME, com.cognos.developer.schemas.bmt._60._7.ExpressionType.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.developer.cognos.com/schemas/bmt/60/7", name = "steward")
    public JAXBElement<String> createSteward(String value) {
        return new JAXBElement<String>(_Steward_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link DataSourceType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.developer.cognos.com/schemas/bmt/60/7", name = "dataSource")
    public JAXBElement<DataSourceType> createDataSource(DataSourceType value) {
        return new JAXBElement<DataSourceType>(_DataSource_QNAME, DataSourceType.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link PackageViewType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.developer.cognos.com/schemas/bmt/60/7", name = "package")
    public JAXBElement<PackageViewType> createPackage(PackageViewType value) {
        return new JAXBElement<PackageViewType>(_Package_QNAME, PackageViewType.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.developer.cognos.com/schemas/bmt/60/7", name = "aliasTableMapRef")
    public JAXBElement<String> createAliasTableMapRef(String value) {
        return new JAXBElement<String>(_AliasTableMapRef_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link ObjectType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.developer.cognos.com/schemas/bmt/60/7", name = "object")
    public JAXBElement<ObjectType> createObject(ObjectType value) {
        return new JAXBElement<ObjectType>(_Object_QNAME, ObjectType.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link ShortcutType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.developer.cognos.com/schemas/bmt/60/7", name = "shortcut")
    public JAXBElement<ShortcutType> createShortcut(ShortcutType value) {
        return new JAXBElement<ShortcutType>(_Shortcut_QNAME, ShortcutType.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link FunctionType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.developer.cognos.com/schemas/bmt/60/7", name = "function")
    public JAXBElement<FunctionType> createFunction(FunctionType value) {
        return new JAXBElement<FunctionType>(_Function_QNAME, FunctionType.class, null, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.developer.cognos.com/schemas/bmt/60/7", name = "refobj", scope = RefobjViaShortcut.class)
    public JAXBElement<String> createRefobjViaShortcutRefobj(String value) {
        return new JAXBElement<String>(_RefobjViaShortcutRefobj_QNAME, String.class, RefobjViaShortcut.class, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link MacroType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.developer.cognos.com/schemas/bmt/60/7", name = "column", scope = SqlType.class)
    public JAXBElement<MacroType> createSqlTypeColumn(MacroType value) {
        return new JAXBElement<MacroType>(_SqlTypeColumn_QNAME, MacroType.class, SqlType.class, value);
    }

    /**
     * Create an instance of {@link javax.xml.bind.JAXBElement }{@code <}{@link MacroType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.developer.cognos.com/schemas/bmt/60/7", name = "table", scope = SqlType.class)
    public JAXBElement<MacroType> createSqlTypeTable(MacroType value) {
        return new JAXBElement<MacroType>(_SqlTypeTable_QNAME, MacroType.class, SqlType.class, value);
    }

}
