//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 10:35:14 AM MDT 
//


package com.cognos.developer.schemas.bmt._60._7;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for orderByType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="orderByType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sortItem" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="refobj" type="{http://www.developer.cognos.com/schemas/bmt/60/7}refType"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="sort" default="ascending">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *                       &lt;enumeration value="ascending"/>
 *                       &lt;enumeration value="descending"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="nullPlacement" default="nullsLast">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *                       &lt;enumeration value="nullsUnspecified"/>
 *                       &lt;enumeration value="nullsFirst"/>
 *                       &lt;enumeration value="nullsLast"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "orderByType", propOrder = {
    "sortItem"
})
public class OrderByType {

    protected List<com.cognos.developer.schemas.bmt._60._7.OrderByType.SortItem> sortItem;

    /**
     * Gets the value of the sortItem property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sortItem property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSortItem().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link com.cognos.developer.schemas.bmt._60._7.OrderByType.SortItem }
     *
     *
     */
    public List<com.cognos.developer.schemas.bmt._60._7.OrderByType.SortItem> getSortItem() {
        if (sortItem == null) {
            sortItem = new ArrayList<com.cognos.developer.schemas.bmt._60._7.OrderByType.SortItem>();
        }
        return this.sortItem;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="refobj" type="{http://www.developer.cognos.com/schemas/bmt/60/7}refType"/>
     *       &lt;/sequence>
     *       &lt;attribute name="sort" default="ascending">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
     *             &lt;enumeration value="ascending"/>
     *             &lt;enumeration value="descending"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="nullPlacement" default="nullsLast">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
     *             &lt;enumeration value="nullsUnspecified"/>
     *             &lt;enumeration value="nullsFirst"/>
     *             &lt;enumeration value="nullsLast"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "refobj"
    })
    public static class SortItem {

        @XmlElement(required = true)
        protected String refobj;
        @XmlAttribute(name = "sort")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String sort;
        @XmlAttribute(name = "nullPlacement")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String nullPlacement;

        /**
         * Gets the value of the refobj property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRefobj() {
            return refobj;
        }

        /**
         * Sets the value of the refobj property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRefobj(String value) {
            this.refobj = value;
        }

        /**
         * Gets the value of the sort property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSort() {
            if (sort == null) {
                return "ascending";
            } else {
                return sort;
            }
        }

        /**
         * Sets the value of the sort property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSort(String value) {
            this.sort = value;
        }

        /**
         * Gets the value of the nullPlacement property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNullPlacement() {
            if (nullPlacement == null) {
                return "nullsLast";
            } else {
                return nullPlacement;
            }
        }

        /**
         * Sets the value of the nullPlacement property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNullPlacement(String value) {
            this.nullPlacement = value;
        }

    }

}
