//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 10:35:14 AM MDT 
//


package com.cognos.developer.schemas.bmt._60._7;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for packageViewType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="packageViewType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.developer.cognos.com/schemas/bmt/60/7}reportObjectType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.developer.cognos.com/schemas/bmt/60/7}packageProperties"/>
 *       &lt;/sequence>
 *       &lt;attribute name="isRoleBased" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "packageViewType", propOrder = {
    "lastPublished",
    "lastPublishedCMPath",
    "maxVersions",
    "locales",
    "definition",
    "adminAccess",
    "isNullSuppressionAllowed",
    "isMultiEdgeNullSuppressionAllowed",
    "isAccessToNullSuppressionOptionsAllowed",
    "useV5DataServer"
})
public class PackageViewType
    extends com.cognos.developer.schemas.bmt._60._7.ReportObjectType
{

    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastPublished;
    protected String lastPublishedCMPath;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger maxVersions;
    @XmlElement(required = true)
    protected com.cognos.developer.schemas.bmt._60._7.SupportedLocalesType locales;
    @XmlElement(required = true)
    protected com.cognos.developer.schemas.bmt._60._7.PackageViewType.Definition definition;
    @XmlElement(required = true)
    protected com.cognos.developer.schemas.bmt._60._7.PackageViewType.AdminAccess adminAccess;
    @XmlElement(defaultValue = "true")
    protected Boolean isNullSuppressionAllowed;
    @XmlElement(defaultValue = "true")
    protected Boolean isMultiEdgeNullSuppressionAllowed;
    @XmlElement(defaultValue = "true")
    protected Boolean isAccessToNullSuppressionOptionsAllowed;
    @XmlElement(defaultValue = "false")
    protected Boolean useV5DataServer;
    @XmlAttribute(name = "isRoleBased")
    protected Boolean isRoleBased;

    /**
     * Gets the value of the lastPublished property.
     *
     * @return
     *     possible object is
     *     {@link javax.xml.datatype.XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getLastPublished() {
        return lastPublished;
    }

    /**
     * Sets the value of the lastPublished property.
     *
     * @param value
     *     allowed object is
     *     {@link javax.xml.datatype.XMLGregorianCalendar }
     *
     */
    public void setLastPublished(XMLGregorianCalendar value) {
        this.lastPublished = value;
    }

    /**
     * Gets the value of the lastPublishedCMPath property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLastPublishedCMPath() {
        return lastPublishedCMPath;
    }

    /**
     * Sets the value of the lastPublishedCMPath property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLastPublishedCMPath(String value) {
        this.lastPublishedCMPath = value;
    }

    /**
     * Gets the value of the maxVersions property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getMaxVersions() {
        return maxVersions;
    }

    /**
     * Sets the value of the maxVersions property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setMaxVersions(BigInteger value) {
        this.maxVersions = value;
    }

    /**
     * Gets the value of the locales property.
     *
     * @return
     *     possible object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.SupportedLocalesType }
     *
     */
    public com.cognos.developer.schemas.bmt._60._7.SupportedLocalesType getLocales() {
        return locales;
    }

    /**
     * Sets the value of the locales property.
     *
     * @param value
     *     allowed object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.SupportedLocalesType }
     *
     */
    public void setLocales(com.cognos.developer.schemas.bmt._60._7.SupportedLocalesType value) {
        this.locales = value;
    }

    /**
     * Gets the value of the definition property.
     *
     * @return
     *     possible object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.PackageViewType.Definition }
     *
     */
    public com.cognos.developer.schemas.bmt._60._7.PackageViewType.Definition getDefinition() {
        return definition;
    }

    /**
     * Sets the value of the definition property.
     *
     * @param value
     *     allowed object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.PackageViewType.Definition }
     *
     */
    public void setDefinition(com.cognos.developer.schemas.bmt._60._7.PackageViewType.Definition value) {
        this.definition = value;
    }

    /**
     * Gets the value of the adminAccess property.
     *
     * @return
     *     possible object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.PackageViewType.AdminAccess }
     *
     */
    public com.cognos.developer.schemas.bmt._60._7.PackageViewType.AdminAccess getAdminAccess() {
        return adminAccess;
    }

    /**
     * Sets the value of the adminAccess property.
     *
     * @param value
     *     allowed object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.PackageViewType.AdminAccess }
     *
     */
    public void setAdminAccess(com.cognos.developer.schemas.bmt._60._7.PackageViewType.AdminAccess value) {
        this.adminAccess = value;
    }

    /**
     * Gets the value of the isNullSuppressionAllowed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsNullSuppressionAllowed() {
        return isNullSuppressionAllowed;
    }

    /**
     * Sets the value of the isNullSuppressionAllowed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsNullSuppressionAllowed(Boolean value) {
        this.isNullSuppressionAllowed = value;
    }

    /**
     * Gets the value of the isMultiEdgeNullSuppressionAllowed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsMultiEdgeNullSuppressionAllowed() {
        return isMultiEdgeNullSuppressionAllowed;
    }

    /**
     * Sets the value of the isMultiEdgeNullSuppressionAllowed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsMultiEdgeNullSuppressionAllowed(Boolean value) {
        this.isMultiEdgeNullSuppressionAllowed = value;
    }

    /**
     * Gets the value of the isAccessToNullSuppressionOptionsAllowed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsAccessToNullSuppressionOptionsAllowed() {
        return isAccessToNullSuppressionOptionsAllowed;
    }

    /**
     * Sets the value of the isAccessToNullSuppressionOptionsAllowed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsAccessToNullSuppressionOptionsAllowed(Boolean value) {
        this.isAccessToNullSuppressionOptionsAllowed = value;
    }

    /**
     * Gets the value of the useV5DataServer property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUseV5DataServer() {
        return useV5DataServer;
    }

    /**
     * Sets the value of the useV5DataServer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseV5DataServer(Boolean value) {
        this.useV5DataServer = value;
    }

    /**
     * Gets the value of the isRoleBased property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsRoleBased() {
        if (isRoleBased == null) {
            return false;
        } else {
            return isRoleBased;
        }
    }

    /**
     * Sets the value of the isRoleBased property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsRoleBased(Boolean value) {
        this.isRoleBased = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.developer.cognos.com/schemas/bmt/60/7}decisionRole" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "decisionRole"
    })
    public static class AdminAccess {

        protected com.cognos.developer.schemas.bmt._60._7.DecisionRoleType decisionRole;

        /**
         * Gets the value of the decisionRole property.
         * 
         * @return
         *     possible object is
         *     {@link com.cognos.developer.schemas.bmt._60._7.DecisionRoleType }
         *     
         */
        public com.cognos.developer.schemas.bmt._60._7.DecisionRoleType getDecisionRole() {
            return decisionRole;
        }

        /**
         * Sets the value of the decisionRole property.
         * 
         * @param value
         *     allowed object is
         *     {@link com.cognos.developer.schemas.bmt._60._7.DecisionRoleType }
         *     
         */
        public void setDecisionRole(com.cognos.developer.schemas.bmt._60._7.DecisionRoleType value) {
            this.decisionRole = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.developer.cognos.com/schemas/bmt/60/7}viewref" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "viewref"
    })
    public static class Definition {

        protected List<String> viewref;

        /**
         * Gets the value of the viewref property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the viewref property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getViewref().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getViewref() {
            if (viewref == null) {
                viewref = new ArrayList<String>();
            }
            return this.viewref;
        }

    }

}
