//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 10:35:14 AM MDT 
//


package com.cognos.developer.schemas.bmt._60._7;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for parameterMapType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="parameterMapType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.developer.cognos.com/schemas/bmt/60/7}modelObjectType">
 *       &lt;sequence>
 *         &lt;element name="defaultValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="loadAsNeeded" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="parameterMapEntry" type="{http://www.developer.cognos.com/schemas/bmt/60/7}parameterMapEntryType" maxOccurs="unbounded"/>
 *           &lt;element name="queryItemMap" type="{http://www.developer.cognos.com/schemas/bmt/60/7}queryItemMapType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="hidden" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "parameterMapType", propOrder = {
    "defaultValue",
    "loadAsNeeded",
    "parameterMapEntry",
    "queryItemMap"
})
public class ParameterMapType
    extends com.cognos.developer.schemas.bmt._60._7.ModelObjectType
{

    protected String defaultValue;
    @XmlElement(defaultValue = "false")
    protected Boolean loadAsNeeded;
    protected List<com.cognos.developer.schemas.bmt._60._7.ParameterMapEntryType> parameterMapEntry;
    protected com.cognos.developer.schemas.bmt._60._7.QueryItemMapType queryItemMap;
    @XmlAttribute(name = "hidden")
    protected Boolean hidden;

    /**
     * Gets the value of the defaultValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultValue() {
        return defaultValue;
    }

    /**
     * Sets the value of the defaultValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultValue(String value) {
        this.defaultValue = value;
    }

    /**
     * Gets the value of the loadAsNeeded property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLoadAsNeeded() {
        return loadAsNeeded;
    }

    /**
     * Sets the value of the loadAsNeeded property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLoadAsNeeded(Boolean value) {
        this.loadAsNeeded = value;
    }

    /**
     * Gets the value of the parameterMapEntry property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the parameterMapEntry property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParameterMapEntry().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link com.cognos.developer.schemas.bmt._60._7.ParameterMapEntryType }
     * 
     * 
     */
    public List<com.cognos.developer.schemas.bmt._60._7.ParameterMapEntryType> getParameterMapEntry() {
        if (parameterMapEntry == null) {
            parameterMapEntry = new ArrayList<com.cognos.developer.schemas.bmt._60._7.ParameterMapEntryType>();
        }
        return this.parameterMapEntry;
    }

    /**
     * Gets the value of the queryItemMap property.
     * 
     * @return
     *     possible object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.QueryItemMapType }
     *     
     */
    public com.cognos.developer.schemas.bmt._60._7.QueryItemMapType getQueryItemMap() {
        return queryItemMap;
    }

    /**
     * Sets the value of the queryItemMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.QueryItemMapType }
     *     
     */
    public void setQueryItemMap(com.cognos.developer.schemas.bmt._60._7.QueryItemMapType value) {
        this.queryItemMap = value;
    }

    /**
     * Gets the value of the hidden property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isHidden() {
        if (hidden == null) {
            return false;
        } else {
            return hidden;
        }
    }

    /**
     * Sets the value of the hidden property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHidden(Boolean value) {
        this.hidden = value;
    }

}
