//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 10:35:14 AM MDT 
//


package com.cognos.developer.schemas.bmt._60._7;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for promptInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="promptInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="promptType" type="{http://www.developer.cognos.com/schemas/bmt/60/7}promptTypeValues"/>
 *         &lt;element name="promptCascadeOnRef" type="{http://www.developer.cognos.com/schemas/bmt/60/7}refType" minOccurs="0"/>
 *         &lt;element name="promptDisplayItemRef" type="{http://www.developer.cognos.com/schemas/bmt/60/7}refType" minOccurs="0"/>
 *         &lt;element name="promptFilterItemRef" type="{http://www.developer.cognos.com/schemas/bmt/60/7}refType" minOccurs="0"/>
 *         &lt;element name="promptUseItemRef" type="{http://www.developer.cognos.com/schemas/bmt/60/7}refType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "promptInfoType", propOrder = {
    "promptType",
    "promptCascadeOnRef",
    "promptDisplayItemRef",
    "promptFilterItemRef",
    "promptUseItemRef"
})
public class PromptInfoType {

    @XmlElement(required = true, defaultValue = "serverDetermined")
    protected com.cognos.developer.schemas.bmt._60._7.PromptTypeValues promptType;
    protected String promptCascadeOnRef;
    protected String promptDisplayItemRef;
    protected String promptFilterItemRef;
    protected String promptUseItemRef;

    /**
     * Gets the value of the promptType property.
     * 
     * @return
     *     possible object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.PromptTypeValues }
     *     
     */
    public com.cognos.developer.schemas.bmt._60._7.PromptTypeValues getPromptType() {
        return promptType;
    }

    /**
     * Sets the value of the promptType property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.PromptTypeValues }
     *     
     */
    public void setPromptType(com.cognos.developer.schemas.bmt._60._7.PromptTypeValues value) {
        this.promptType = value;
    }

    /**
     * Gets the value of the promptCascadeOnRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPromptCascadeOnRef() {
        return promptCascadeOnRef;
    }

    /**
     * Sets the value of the promptCascadeOnRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPromptCascadeOnRef(String value) {
        this.promptCascadeOnRef = value;
    }

    /**
     * Gets the value of the promptDisplayItemRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPromptDisplayItemRef() {
        return promptDisplayItemRef;
    }

    /**
     * Sets the value of the promptDisplayItemRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPromptDisplayItemRef(String value) {
        this.promptDisplayItemRef = value;
    }

    /**
     * Gets the value of the promptFilterItemRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPromptFilterItemRef() {
        return promptFilterItemRef;
    }

    /**
     * Sets the value of the promptFilterItemRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPromptFilterItemRef(String value) {
        this.promptFilterItemRef = value;
    }

    /**
     * Gets the value of the promptUseItemRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPromptUseItemRef() {
        return promptUseItemRef;
    }

    /**
     * Sets the value of the promptUseItemRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPromptUseItemRef(String value) {
        this.promptUseItemRef = value;
    }

}
