//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 10:35:14 AM MDT 
//


package com.cognos.developer.schemas.bmt._60._7;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for promptTypeValues.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="promptTypeValues">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="serverDetermined"/>
 *     &lt;enumeration value="editBox"/>
 *     &lt;enumeration value="selectDate"/>
 *     &lt;enumeration value="selectDateTime"/>
 *     &lt;enumeration value="selectInterval"/>
 *     &lt;enumeration value="selectTime"/>
 *     &lt;enumeration value="selectValue"/>
 *     &lt;enumeration value="selectWithSearch"/>
 *     &lt;enumeration value="selectWithTree"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "promptTypeValues")
@XmlEnum
public enum PromptTypeValues {


    /**
     * Specifies that the prompt will be determined by the server during execution.
     * 
     */
    @XmlEnumValue("serverDetermined")
    SERVER_DETERMINED("serverDetermined"),

    /**
     * Specifies that the prompt will be displayed as an edit box.
     * 
     */
    @XmlEnumValue("editBox")
    EDIT_BOX("editBox"),

    /**
     * Specifies that the prompt will display a selectable date.
     * 
     */
    @XmlEnumValue("selectDate")
    SELECT_DATE("selectDate"),

    /**
     * Specifies that the prompt will display a selectable date and time.
     * 
     */
    @XmlEnumValue("selectDateTime")
    SELECT_DATE_TIME("selectDateTime"),

    /**
     * Specifies that the prompt will display a selectable interval.
     * 
     */
    @XmlEnumValue("selectInterval")
    SELECT_INTERVAL("selectInterval"),

    /**
     * Specifies that the prompt will display a selectable time.
     * 
     */
    @XmlEnumValue("selectTime")
    SELECT_TIME("selectTime"),

    /**
     * Specifies that the prompt will display a list of values from which the user can select.
     * 
     */
    @XmlEnumValue("selectValue")
    SELECT_VALUE("selectValue"),

    /**
     * 
     * 						
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;para xmlns:bmtcr1="http://www.developer.cognos.com/schemas/bmt/60/7" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Specifies that the prompt will be displayed as a user-defined search.&lt;/para&gt;
     * </pre>
     * 
     * 						
     * <pre>
     * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;para xmlns:bmtcr1="http://www.developer.cognos.com/schemas/bmt/60/7" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Note: Not applicable to a queryItem where usage is set to fact.&lt;/para&gt;
     * </pre>
     * 
     * 					
     * 
     */
    @XmlEnumValue("selectWithSearch")
    SELECT_WITH_SEARCH("selectWithSearch"),
    @XmlEnumValue("selectWithTree")
    SELECT_WITH_TREE("selectWithTree");
    private final String value;

    PromptTypeValues(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static com.cognos.developer.schemas.bmt._60._7.PromptTypeValues fromValue(String v) {
        for (com.cognos.developer.schemas.bmt._60._7.PromptTypeValues c: com.cognos.developer.schemas.bmt._60._7.PromptTypeValues.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
