//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 10:35:14 AM MDT 
//


package com.cognos.developer.schemas.bmt._60._7;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for querySubjectType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="querySubjectType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.developer.cognos.com/schemas/bmt/60/7}reportObjectType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.developer.cognos.com/schemas/bmt/60/7}querySubjectProperties" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="status" type="{http://www.developer.cognos.com/schemas/bmt/60/7}statusType" default="valid" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "querySubjectType", propOrder = {
    "definition",
    "levels",
    "hierarchies",
    "previewFilters",
    "securityFilters",
    "externalizeMethod",
    "externalizeAutoSummary",
    "useInJoinPath",
    "orderOfMagnitude",
    "numberOfRows"
})
@XmlSeeAlso({
    Dimension.class,
    com.cognos.developer.schemas.bmt._60._7.QuerySubject.class
})
public class QuerySubjectType
    extends ReportObjectType
{

    protected com.cognos.developer.schemas.bmt._60._7.DefinitionType definition;
    protected com.cognos.developer.schemas.bmt._60._7.QuerySubjectType.Levels levels;
    protected com.cognos.developer.schemas.bmt._60._7.QuerySubjectType.Hierarchies hierarchies;
    protected com.cognos.developer.schemas.bmt._60._7.QuerySubjectType.PreviewFilters previewFilters;
    protected com.cognos.developer.schemas.bmt._60._7.QuerySubjectType.SecurityFilters securityFilters;
    @XmlElement(defaultValue = "default")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String externalizeMethod;
    @XmlElement(defaultValue = "false")
    protected Boolean externalizeAutoSummary;
    @XmlElement(defaultValue = "false")
    protected Boolean useInJoinPath;
    @XmlElement(defaultValue = "0")
    protected BigInteger orderOfMagnitude;
    protected BigInteger numberOfRows;
    @XmlAttribute(name = "status")
    protected StatusType status;

    /**
     * Gets the value of the definition property.
     *
     * @return
     *     possible object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.DefinitionType }
     *
     */
    public com.cognos.developer.schemas.bmt._60._7.DefinitionType getDefinition() {
        return definition;
    }

    /**
     * Sets the value of the definition property.
     *
     * @param value
     *     allowed object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.DefinitionType }
     *
     */
    public void setDefinition(com.cognos.developer.schemas.bmt._60._7.DefinitionType value) {
        this.definition = value;
    }

    /**
     * Gets the value of the levels property.
     *
     * @return
     *     possible object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.QuerySubjectType.Levels }
     *
     */
    public com.cognos.developer.schemas.bmt._60._7.QuerySubjectType.Levels getLevels() {
        return levels;
    }

    /**
     * Sets the value of the levels property.
     *
     * @param value
     *     allowed object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.QuerySubjectType.Levels }
     *
     */
    public void setLevels(com.cognos.developer.schemas.bmt._60._7.QuerySubjectType.Levels value) {
        this.levels = value;
    }

    /**
     * Gets the value of the hierarchies property.
     *
     * @return
     *     possible object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.QuerySubjectType.Hierarchies }
     *
     */
    public com.cognos.developer.schemas.bmt._60._7.QuerySubjectType.Hierarchies getHierarchies() {
        return hierarchies;
    }

    /**
     * Sets the value of the hierarchies property.
     *
     * @param value
     *     allowed object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.QuerySubjectType.Hierarchies }
     *
     */
    public void setHierarchies(com.cognos.developer.schemas.bmt._60._7.QuerySubjectType.Hierarchies value) {
        this.hierarchies = value;
    }

    /**
     * Gets the value of the previewFilters property.
     *
     * @return
     *     possible object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.QuerySubjectType.PreviewFilters }
     *
     */
    public com.cognos.developer.schemas.bmt._60._7.QuerySubjectType.PreviewFilters getPreviewFilters() {
        return previewFilters;
    }

    /**
     * Sets the value of the previewFilters property.
     *
     * @param value
     *     allowed object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.QuerySubjectType.PreviewFilters }
     *
     */
    public void setPreviewFilters(com.cognos.developer.schemas.bmt._60._7.QuerySubjectType.PreviewFilters value) {
        this.previewFilters = value;
    }

    /**
     * Gets the value of the securityFilters property.
     *
     * @return
     *     possible object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.QuerySubjectType.SecurityFilters }
     *
     */
    public com.cognos.developer.schemas.bmt._60._7.QuerySubjectType.SecurityFilters getSecurityFilters() {
        return securityFilters;
    }

    /**
     * Sets the value of the securityFilters property.
     *
     * @param value
     *     allowed object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.QuerySubjectType.SecurityFilters }
     *
     */
    public void setSecurityFilters(com.cognos.developer.schemas.bmt._60._7.QuerySubjectType.SecurityFilters value) {
        this.securityFilters = value;
    }

    /**
     * Gets the value of the externalizeMethod property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getExternalizeMethod() {
        return externalizeMethod;
    }

    /**
     * Sets the value of the externalizeMethod property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setExternalizeMethod(String value) {
        this.externalizeMethod = value;
    }

    /**
     * Gets the value of the externalizeAutoSummary property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isExternalizeAutoSummary() {
        return externalizeAutoSummary;
    }

    /**
     * Sets the value of the externalizeAutoSummary property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setExternalizeAutoSummary(Boolean value) {
        this.externalizeAutoSummary = value;
    }

    /**
     * Gets the value of the useInJoinPath property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isUseInJoinPath() {
        return useInJoinPath;
    }

    /**
     * Sets the value of the useInJoinPath property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setUseInJoinPath(Boolean value) {
        this.useInJoinPath = value;
    }

    /**
     * Gets the value of the orderOfMagnitude property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getOrderOfMagnitude() {
        return orderOfMagnitude;
    }

    /**
     * Sets the value of the orderOfMagnitude property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setOrderOfMagnitude(BigInteger value) {
        this.orderOfMagnitude = value;
    }

    /**
     * Gets the value of the numberOfRows property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getNumberOfRows() {
        return numberOfRows;
    }

    /**
     * Sets the value of the numberOfRows property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setNumberOfRows(BigInteger value) {
        this.numberOfRows = value;
    }

    /**
     * Gets the value of the status property.
     *
     * @return
     *     possible object is
     *     {@link StatusType }
     *
     */
    public StatusType getStatus() {
        if (status == null) {
            return StatusType.VALID;
        } else {
            return status;
        }
    }

    /**
     * Sets the value of the status property.
     *
     * @param value
     *     allowed object is
     *     {@link StatusType }
     *
     */
    public void setStatus(StatusType value) {
        this.status = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="_hierarchy" type="{http://www.developer.cognos.com/schemas/bmt/60/7}_hierarchyType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "hierarchy"
    })
    public static class Hierarchies {

        @XmlElement(name = "_hierarchy")
        protected List<HierarchyType> hierarchy;

        /**
         * Gets the value of the hierarchy property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the hierarchy property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getHierarchy().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link HierarchyType }
         *
         *
         */
        public List<HierarchyType> getHierarchy() {
            if (hierarchy == null) {
                hierarchy = new ArrayList<HierarchyType>();
            }
            return this.hierarchy;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="_level" type="{http://www.developer.cognos.com/schemas/bmt/60/7}_determinantType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "level"
    })
    public static class Levels {

        @XmlElement(name = "_level")
        protected List<DeterminantType2> level;

        /**
         * Gets the value of the level property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the level property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLevel().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DeterminantType2 }
         *
         *
         */
        public List<DeterminantType2> getLevel() {
            if (level == null) {
                level = new ArrayList<DeterminantType2>();
            }
            return this.level;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="previewFilter">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;choice>
     *                   &lt;element name="refobj" type="{http://www.developer.cognos.com/schemas/bmt/60/7}refType"/>
     *                   &lt;sequence>
     *                     &lt;element name="displayName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                     &lt;element ref="{http://www.developer.cognos.com/schemas/bmt/60/7}expression"/>
     *                   &lt;/sequence>
     *                 &lt;/choice>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "previewFilter"
    })
    public static class PreviewFilters {

        protected List<com.cognos.developer.schemas.bmt._60._7.QuerySubjectType.PreviewFilters.PreviewFilter> previewFilter;

        /**
         * Gets the value of the previewFilter property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the previewFilter property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPreviewFilter().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link com.cognos.developer.schemas.bmt._60._7.QuerySubjectType.PreviewFilters.PreviewFilter }
         *
         *
         */
        public List<com.cognos.developer.schemas.bmt._60._7.QuerySubjectType.PreviewFilters.PreviewFilter> getPreviewFilter() {
            if (previewFilter == null) {
                previewFilter = new ArrayList<com.cognos.developer.schemas.bmt._60._7.QuerySubjectType.PreviewFilters.PreviewFilter>();
            }
            return this.previewFilter;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;choice>
         *         &lt;element name="refobj" type="{http://www.developer.cognos.com/schemas/bmt/60/7}refType"/>
         *         &lt;sequence>
         *           &lt;element name="displayName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *           &lt;element ref="{http://www.developer.cognos.com/schemas/bmt/60/7}expression"/>
         *         &lt;/sequence>
         *       &lt;/choice>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "refobj",
            "displayName",
            "expression"
        })
        public static class PreviewFilter {

            protected String refobj;
            protected String displayName;
            protected com.cognos.developer.schemas.bmt._60._7.ExpressionType expression;

            /**
             * Gets the value of the refobj property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRefobj() {
                return refobj;
            }

            /**
             * Sets the value of the refobj property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRefobj(String value) {
                this.refobj = value;
            }

            /**
             * Gets the value of the displayName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDisplayName() {
                return displayName;
            }

            /**
             * Sets the value of the displayName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDisplayName(String value) {
                this.displayName = value;
            }

            /**
             * Gets the value of the expression property.
             * 
             * @return
             *     possible object is
             *     {@link com.cognos.developer.schemas.bmt._60._7.ExpressionType }
             *     
             */
            public com.cognos.developer.schemas.bmt._60._7.ExpressionType getExpression() {
                return expression;
            }

            /**
             * Sets the value of the expression property.
             * 
             * @param value
             *     allowed object is
             *     {@link com.cognos.developer.schemas.bmt._60._7.ExpressionType }
             *     
             */
            public void setExpression(com.cognos.developer.schemas.bmt._60._7.ExpressionType value) {
                this.expression = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="securityFilterDefinition" type="{http://www.developer.cognos.com/schemas/bmt/60/7}securityFilterDefinitionType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "securityFilterDefinition"
    })
    public static class SecurityFilters {

        protected List<SecurityFilterDefinitionType> securityFilterDefinition;

        /**
         * Gets the value of the securityFilterDefinition property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the securityFilterDefinition property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSecurityFilterDefinition().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SecurityFilterDefinitionType }
         * 
         * 
         */
        public List<SecurityFilterDefinitionType> getSecurityFilterDefinition() {
            if (securityFilterDefinition == null) {
                securityFilterDefinition = new ArrayList<SecurityFilterDefinitionType>();
            }
            return this.securityFilterDefinition;
        }

    }

}
