//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 10:35:14 AM MDT 
//


package com.cognos.developer.schemas.bmt._60._7;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for queryItemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="queryItemType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.developer.cognos.com/schemas/bmt/60/7}reportObjectType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.developer.cognos.com/schemas/bmt/60/7}queryItemProperties" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "queryItemType", propOrder = {
    "expression",
    "externalName",
    "hidden",
    "usage",
    "format",
    "currency",
    "datatype",
    "precision",
    "scale",
    "size",
    "nullable",
    "aggregationRule",
    "displayType",
    "mimeType",
    "promptInfo",
    "regularAggregate",
    "semiAggregate",
    "sortOnRef",
    "unSortable",
    "sort",
    "roles",
    "conformanceRef",
    "collationSequenceName",
    "collationSequenceLevel",
    "originalCollationSequenceName",
    "originalEncodingName"
})
@XmlSeeAlso({
    com.cognos.developer.schemas.bmt._60._7.QueryItem.class,
    Measure.class
})
public class QueryItemType
    extends com.cognos.developer.schemas.bmt._60._7.ReportObjectType
{

    protected com.cognos.developer.schemas.bmt._60._7.ExpressionType expression;
    protected String externalName;
    @XmlElement(defaultValue = "false")
    protected Boolean hidden;
    @XmlElement(defaultValue = "unknown")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String usage;
    protected String format;
    protected String currency;
    @XmlElement(defaultValue = "unknown")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String datatype;
    protected BigInteger precision;
    @XmlElement(defaultValue = "0")
    protected BigInteger scale;
    protected Long size;
    @XmlElement(defaultValue = "false")
    protected Boolean nullable;
    protected RegularAggregateType aggregationRule;
    @XmlElement(defaultValue = "value")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String displayType;
    @XmlElement(name = "MIMEType")
    protected String mimeType;
    protected com.cognos.developer.schemas.bmt._60._7.PromptInfoType promptInfo;
    @XmlElement(defaultValue = "unsupported")
    protected RegularAggregateType regularAggregate;
    @XmlElement(defaultValue = "unsupported")
    protected RegularAggregateType semiAggregate;
    protected String sortOnRef;
    @XmlElement(defaultValue = "false")
    protected Boolean unSortable;
    @XmlElement(defaultValue = "none")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String sort;
    protected com.cognos.developer.schemas.bmt._60._7.QueryItemType.Roles roles;
    protected String conformanceRef;
    protected String collationSequenceName;
    protected BigInteger collationSequenceLevel;
    protected String originalCollationSequenceName;
    protected String originalEncodingName;

    /**
     * Gets the value of the expression property.
     *
     * @return
     *     possible object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.ExpressionType }
     *
     */
    public com.cognos.developer.schemas.bmt._60._7.ExpressionType getExpression() {
        return expression;
    }

    /**
     * Sets the value of the expression property.
     *
     * @param value
     *     allowed object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.ExpressionType }
     *
     */
    public void setExpression(com.cognos.developer.schemas.bmt._60._7.ExpressionType value) {
        this.expression = value;
    }

    /**
     * Gets the value of the externalName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getExternalName() {
        return externalName;
    }

    /**
     * Sets the value of the externalName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setExternalName(String value) {
        this.externalName = value;
    }

    /**
     * Gets the value of the hidden property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isHidden() {
        return hidden;
    }

    /**
     * Sets the value of the hidden property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setHidden(Boolean value) {
        this.hidden = value;
    }

    /**
     * Gets the value of the usage property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getUsage() {
        return usage;
    }

    /**
     * Sets the value of the usage property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setUsage(String value) {
        this.usage = value;
    }

    /**
     * Gets the value of the format property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFormat() {
        return format;
    }

    /**
     * Sets the value of the format property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFormat(String value) {
        this.format = value;
    }

    /**
     * Gets the value of the currency property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the datatype property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDatatype() {
        return datatype;
    }

    /**
     * Sets the value of the datatype property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDatatype(String value) {
        this.datatype = value;
    }

    /**
     * Gets the value of the precision property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getPrecision() {
        return precision;
    }

    /**
     * Sets the value of the precision property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setPrecision(BigInteger value) {
        this.precision = value;
    }

    /**
     * Gets the value of the scale property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getScale() {
        return scale;
    }

    /**
     * Sets the value of the scale property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setScale(BigInteger value) {
        this.scale = value;
    }

    /**
     * Gets the value of the size property.
     *
     * @return
     *     possible object is
     *     {@link Long }
     *
     */
    public Long getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     *
     * @param value
     *     allowed object is
     *     {@link Long }
     *
     */
    public void setSize(Long value) {
        this.size = value;
    }

    /**
     * Gets the value of the nullable property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isNullable() {
        return nullable;
    }

    /**
     * Sets the value of the nullable property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setNullable(Boolean value) {
        this.nullable = value;
    }

    /**
     * Gets the value of the aggregationRule property.
     *
     * @return
     *     possible object is
     *     {@link RegularAggregateType }
     *
     */
    public RegularAggregateType getAggregationRule() {
        return aggregationRule;
    }

    /**
     * Sets the value of the aggregationRule property.
     *
     * @param value
     *     allowed object is
     *     {@link RegularAggregateType }
     *
     */
    public void setAggregationRule(RegularAggregateType value) {
        this.aggregationRule = value;
    }

    /**
     * Gets the value of the displayType property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDisplayType() {
        return displayType;
    }

    /**
     * Sets the value of the displayType property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDisplayType(String value) {
        this.displayType = value;
    }

    /**
     * Gets the value of the mimeType property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMIMEType() {
        return mimeType;
    }

    /**
     * Sets the value of the mimeType property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMIMEType(String value) {
        this.mimeType = value;
    }

    /**
     * Gets the value of the promptInfo property.
     *
     * @return
     *     possible object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.PromptInfoType }
     *
     */
    public com.cognos.developer.schemas.bmt._60._7.PromptInfoType getPromptInfo() {
        return promptInfo;
    }

    /**
     * Sets the value of the promptInfo property.
     *
     * @param value
     *     allowed object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.PromptInfoType }
     *
     */
    public void setPromptInfo(com.cognos.developer.schemas.bmt._60._7.PromptInfoType value) {
        this.promptInfo = value;
    }

    /**
     * Gets the value of the regularAggregate property.
     *
     * @return
     *     possible object is
     *     {@link RegularAggregateType }
     *
     */
    public RegularAggregateType getRegularAggregate() {
        return regularAggregate;
    }

    /**
     * Sets the value of the regularAggregate property.
     *
     * @param value
     *     allowed object is
     *     {@link RegularAggregateType }
     *
     */
    public void setRegularAggregate(RegularAggregateType value) {
        this.regularAggregate = value;
    }

    /**
     * Gets the value of the semiAggregate property.
     *
     * @return
     *     possible object is
     *     {@link RegularAggregateType }
     *
     */
    public RegularAggregateType getSemiAggregate() {
        return semiAggregate;
    }

    /**
     * Sets the value of the semiAggregate property.
     *
     * @param value
     *     allowed object is
     *     {@link RegularAggregateType }
     *
     */
    public void setSemiAggregate(RegularAggregateType value) {
        this.semiAggregate = value;
    }

    /**
     * Gets the value of the sortOnRef property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSortOnRef() {
        return sortOnRef;
    }

    /**
     * Sets the value of the sortOnRef property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSortOnRef(String value) {
        this.sortOnRef = value;
    }

    /**
     * Gets the value of the unSortable property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isUnSortable() {
        return unSortable;
    }

    /**
     * Sets the value of the unSortable property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setUnSortable(Boolean value) {
        this.unSortable = value;
    }

    /**
     * Gets the value of the sort property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSort() {
        return sort;
    }

    /**
     * Sets the value of the sort property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSort(String value) {
        this.sort = value;
    }

    /**
     * Gets the value of the roles property.
     *
     * @return
     *     possible object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.QueryItemType.Roles }
     *
     */
    public com.cognos.developer.schemas.bmt._60._7.QueryItemType.Roles getRoles() {
        return roles;
    }

    /**
     * Sets the value of the roles property.
     *
     * @param value
     *     allowed object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.QueryItemType.Roles }
     *
     */
    public void setRoles(com.cognos.developer.schemas.bmt._60._7.QueryItemType.Roles value) {
        this.roles = value;
    }

    /**
     * Gets the value of the conformanceRef property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getConformanceRef() {
        return conformanceRef;
    }

    /**
     * Sets the value of the conformanceRef property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setConformanceRef(String value) {
        this.conformanceRef = value;
    }

    /**
     * Gets the value of the collationSequenceName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCollationSequenceName() {
        return collationSequenceName;
    }

    /**
     * Sets the value of the collationSequenceName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCollationSequenceName(String value) {
        this.collationSequenceName = value;
    }

    /**
     * Gets the value of the collationSequenceLevel property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getCollationSequenceLevel() {
        return collationSequenceLevel;
    }

    /**
     * Sets the value of the collationSequenceLevel property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setCollationSequenceLevel(BigInteger value) {
        this.collationSequenceLevel = value;
    }

    /**
     * Gets the value of the originalCollationSequenceName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getOriginalCollationSequenceName() {
        return originalCollationSequenceName;
    }

    /**
     * Sets the value of the originalCollationSequenceName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setOriginalCollationSequenceName(String value) {
        this.originalCollationSequenceName = value;
    }

    /**
     * Gets the value of the originalEncodingName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getOriginalEncodingName() {
        return originalEncodingName;
    }

    /**
     * Sets the value of the originalEncodingName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setOriginalEncodingName(String value) {
        this.originalEncodingName = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="role" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="name" type="{http://www.developer.cognos.com/schemas/bmt/60/7}nameType" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="intrinsic" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "role"
    })
    public static class Roles {

        protected List<com.cognos.developer.schemas.bmt._60._7.QueryItemType.Roles.Role> role;

        /**
         * Gets the value of the role property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the role property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRole().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link com.cognos.developer.schemas.bmt._60._7.QueryItemType.Roles.Role }
         *
         *
         */
        public List<com.cognos.developer.schemas.bmt._60._7.QueryItemType.Roles.Role> getRole() {
            if (role == null) {
                role = new ArrayList<com.cognos.developer.schemas.bmt._60._7.QueryItemType.Roles.Role>();
            }
            return this.role;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="name" type="{http://www.developer.cognos.com/schemas/bmt/60/7}nameType" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *       &lt;attribute name="intrinsic" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name"
        })
        public static class Role {

            @XmlElement(required = true)
            protected List<com.cognos.developer.schemas.bmt._60._7.NameType> name;
            @XmlAttribute(name = "intrinsic")
            protected Boolean intrinsic;

            /**
             * Gets the value of the name property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the name property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getName().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link com.cognos.developer.schemas.bmt._60._7.NameType }
             * 
             * 
             */
            public List<com.cognos.developer.schemas.bmt._60._7.NameType> getName() {
                if (name == null) {
                    name = new ArrayList<com.cognos.developer.schemas.bmt._60._7.NameType>();
                }
                return this.name;
            }

            /**
             * Gets the value of the intrinsic property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public boolean isIntrinsic() {
                if (intrinsic == null) {
                    return false;
                } else {
                    return intrinsic;
                }
            }

            /**
             * Sets the value of the intrinsic property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setIntrinsic(Boolean value) {
                this.intrinsic = value;
            }

        }

    }

}
