//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 10:35:14 AM MDT 
//


package com.cognos.developer.schemas.bmt._60._7;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for relationshipType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="relationshipType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.developer.cognos.com/schemas/bmt/60/7}modelObjectType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.developer.cognos.com/schemas/bmt/60/7}relationshipProperties"/>
 *       &lt;/sequence>
 *       &lt;attribute name="status" type="{http://www.developer.cognos.com/schemas/bmt/60/7}statusType" default="valid" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "relationshipType", propOrder = {
    "expression",
    "sql",
    "left",
    "right",
    "joinFilterType"
})
public class RelationshipType
    extends com.cognos.developer.schemas.bmt._60._7.ModelObjectType
{

    @XmlElement(required = true)
    protected com.cognos.developer.schemas.bmt._60._7.ExpressionType expression;
    protected com.cognos.developer.schemas.bmt._60._7.SqlType sql;
    @XmlElement(required = true)
    protected com.cognos.developer.schemas.bmt._60._7.CardinalityType left;
    @XmlElement(required = true)
    protected com.cognos.developer.schemas.bmt._60._7.CardinalityType right;
    @XmlElement(defaultValue = "none")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String joinFilterType;
    @XmlAttribute(name = "status")
    protected com.cognos.developer.schemas.bmt._60._7.StatusType status;

    /**
     * Gets the value of the expression property.
     * 
     * @return
     *     possible object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.ExpressionType }
     *     
     */
    public com.cognos.developer.schemas.bmt._60._7.ExpressionType getExpression() {
        return expression;
    }

    /**
     * Sets the value of the expression property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.ExpressionType }
     *     
     */
    public void setExpression(com.cognos.developer.schemas.bmt._60._7.ExpressionType value) {
        this.expression = value;
    }

    /**
     * Gets the value of the sql property.
     * 
     * @return
     *     possible object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.SqlType }
     *     
     */
    public com.cognos.developer.schemas.bmt._60._7.SqlType getSql() {
        return sql;
    }

    /**
     * Sets the value of the sql property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.SqlType }
     *     
     */
    public void setSql(com.cognos.developer.schemas.bmt._60._7.SqlType value) {
        this.sql = value;
    }

    /**
     * Gets the value of the left property.
     * 
     * @return
     *     possible object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.CardinalityType }
     *     
     */
    public com.cognos.developer.schemas.bmt._60._7.CardinalityType getLeft() {
        return left;
    }

    /**
     * Sets the value of the left property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.CardinalityType }
     *     
     */
    public void setLeft(com.cognos.developer.schemas.bmt._60._7.CardinalityType value) {
        this.left = value;
    }

    /**
     * Gets the value of the right property.
     * 
     * @return
     *     possible object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.CardinalityType }
     *     
     */
    public com.cognos.developer.schemas.bmt._60._7.CardinalityType getRight() {
        return right;
    }

    /**
     * Sets the value of the right property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.CardinalityType }
     *     
     */
    public void setRight(com.cognos.developer.schemas.bmt._60._7.CardinalityType value) {
        this.right = value;
    }

    /**
     * Gets the value of the joinFilterType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJoinFilterType() {
        return joinFilterType;
    }

    /**
     * Sets the value of the joinFilterType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJoinFilterType(String value) {
        this.joinFilterType = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.StatusType }
     *     
     */
    public com.cognos.developer.schemas.bmt._60._7.StatusType getStatus() {
        if (status == null) {
            return com.cognos.developer.schemas.bmt._60._7.StatusType.VALID;
        } else {
            return status;
        }
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.cognos.developer.schemas.bmt._60._7.StatusType }
     *     
     */
    public void setStatus(com.cognos.developer.schemas.bmt._60._7.StatusType value) {
        this.status = value;
    }

}
