//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 10:35:14 AM MDT 
//


package com.cognos.developer.schemas.bmt._60._7;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * TO DO This needs to be normalized with the relationship object.
 * 
 * <p>Java class for scopeRelationshipType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="scopeRelationshipType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.developer.cognos.com/schemas/bmt/60/7}modelObjectType">
 *       &lt;sequence>
 *         &lt;element name="left" type="{http://www.developer.cognos.com/schemas/bmt/60/7}cardinalityType"/>
 *         &lt;element name="right" type="{http://www.developer.cognos.com/schemas/bmt/60/7}cardinalityType"/>
 *         &lt;element name="scope" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="levelRef" type="{http://www.developer.cognos.com/schemas/bmt/60/7}refType"/>
 *                   &lt;element name="measureScope" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="rollup" type="{http://www.developer.cognos.com/schemas/bmt/60/7}regularAggregateType" minOccurs="0"/>
 *                             &lt;element name="allocation" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *                                   &lt;enumeration value="doNotAllocate"/>
 *                                   &lt;enumeration value="constant"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="refobj" type="{http://www.developer.cognos.com/schemas/bmt/60/7}refType"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="excluded" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "scopeRelationshipType", propOrder = {
    "left",
    "right",
    "scope"
})
public class ScopeRelationshipType
    extends ModelObjectType
{

    @XmlElement(required = true)
    protected CardinalityType left;
    @XmlElement(required = true)
    protected CardinalityType right;
    protected List<com.cognos.developer.schemas.bmt._60._7.ScopeRelationshipType.Scope> scope;

    /**
     * Gets the value of the left property.
     *
     * @return
     *     possible object is
     *     {@link CardinalityType }
     *
     */
    public CardinalityType getLeft() {
        return left;
    }

    /**
     * Sets the value of the left property.
     *
     * @param value
     *     allowed object is
     *     {@link CardinalityType }
     *
     */
    public void setLeft(CardinalityType value) {
        this.left = value;
    }

    /**
     * Gets the value of the right property.
     *
     * @return
     *     possible object is
     *     {@link CardinalityType }
     *
     */
    public CardinalityType getRight() {
        return right;
    }

    /**
     * Sets the value of the right property.
     *
     * @param value
     *     allowed object is
     *     {@link CardinalityType }
     *
     */
    public void setRight(CardinalityType value) {
        this.right = value;
    }

    /**
     * Gets the value of the scope property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the scope property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScope().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link com.cognos.developer.schemas.bmt._60._7.ScopeRelationshipType.Scope }
     *
     *
     */
    public List<com.cognos.developer.schemas.bmt._60._7.ScopeRelationshipType.Scope> getScope() {
        if (scope == null) {
            scope = new ArrayList<com.cognos.developer.schemas.bmt._60._7.ScopeRelationshipType.Scope>();
        }
        return this.scope;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="levelRef" type="{http://www.developer.cognos.com/schemas/bmt/60/7}refType"/>
     *         &lt;element name="measureScope" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="rollup" type="{http://www.developer.cognos.com/schemas/bmt/60/7}regularAggregateType" minOccurs="0"/>
     *                   &lt;element name="allocation" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
     *                         &lt;enumeration value="doNotAllocate"/>
     *                         &lt;enumeration value="constant"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="refobj" type="{http://www.developer.cognos.com/schemas/bmt/60/7}refType"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="excluded" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "levelRef",
        "measureScope"
    })
    public static class Scope {

        @XmlElement(required = true)
        protected String levelRef;
        @XmlElement(required = true)
        protected List<com.cognos.developer.schemas.bmt._60._7.ScopeRelationshipType.Scope.MeasureScope> measureScope;

        /**
         * Gets the value of the levelRef property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getLevelRef() {
            return levelRef;
        }

        /**
         * Sets the value of the levelRef property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setLevelRef(String value) {
            this.levelRef = value;
        }

        /**
         * Gets the value of the measureScope property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the measureScope property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMeasureScope().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link com.cognos.developer.schemas.bmt._60._7.ScopeRelationshipType.Scope.MeasureScope }
         *
         *
         */
        public List<com.cognos.developer.schemas.bmt._60._7.ScopeRelationshipType.Scope.MeasureScope> getMeasureScope() {
            if (measureScope == null) {
                measureScope = new ArrayList<com.cognos.developer.schemas.bmt._60._7.ScopeRelationshipType.Scope.MeasureScope>();
            }
            return this.measureScope;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="rollup" type="{http://www.developer.cognos.com/schemas/bmt/60/7}regularAggregateType" minOccurs="0"/>
         *         &lt;element name="allocation" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
         *               &lt;enumeration value="doNotAllocate"/>
         *               &lt;enumeration value="constant"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="refobj" type="{http://www.developer.cognos.com/schemas/bmt/60/7}refType"/>
         *       &lt;/sequence>
         *       &lt;attribute name="excluded" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "rollup",
            "allocation",
            "refobj"
        })
        public static class MeasureScope {

            protected RegularAggregateType rollup;
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            protected String allocation;
            @XmlElement(required = true)
            protected String refobj;
            @XmlAttribute(name = "excluded")
            protected Boolean excluded;

            /**
             * Gets the value of the rollup property.
             * 
             * @return
             *     possible object is
             *     {@link RegularAggregateType }
             *     
             */
            public RegularAggregateType getRollup() {
                return rollup;
            }

            /**
             * Sets the value of the rollup property.
             * 
             * @param value
             *     allowed object is
             *     {@link RegularAggregateType }
             *     
             */
            public void setRollup(RegularAggregateType value) {
                this.rollup = value;
            }

            /**
             * Gets the value of the allocation property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAllocation() {
                return allocation;
            }

            /**
             * Sets the value of the allocation property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAllocation(String value) {
                this.allocation = value;
            }

            /**
             * Gets the value of the refobj property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRefobj() {
                return refobj;
            }

            /**
             * Sets the value of the refobj property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRefobj(String value) {
                this.refobj = value;
            }

            /**
             * Gets the value of the excluded property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public boolean isExcluded() {
                if (excluded == null) {
                    return false;
                } else {
                    return excluded;
                }
            }

            /**
             * Sets the value of the excluded property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setExcluded(Boolean value) {
                this.excluded = value;
            }

        }

    }

}
