//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 10:35:14 AM MDT 
//


package com.cognos.developer.schemas.bmt._60._7;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for sectionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sectionType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.developer.cognos.com/schemas/bmt/60/7}reportObjectType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{http://www.developer.cognos.com/schemas/bmt/60/7}folder"/>
 *           &lt;element ref="{http://www.developer.cognos.com/schemas/bmt/60/7}function"/>
 *           &lt;element ref="{http://www.developer.cognos.com/schemas/bmt/60/7}namespace"/>
 *           &lt;element ref="{http://www.developer.cognos.com/schemas/bmt/60/7}object"/>
 *           &lt;element ref="{http://www.developer.cognos.com/schemas/bmt/60/7}shortcut"/>
 *           &lt;element ref="{http://www.developer.cognos.com/schemas/bmt/60/7}querySubject"/>
 *           &lt;element ref="{http://www.developer.cognos.com/schemas/bmt/60/7}updateSubject"/>
 *           &lt;element ref="{http://www.developer.cognos.com/schemas/bmt/60/7}relationship"/>
 *           &lt;element ref="{http://www.developer.cognos.com/schemas/bmt/60/7}relationshipShortcut"/>
 *           &lt;element ref="{http://www.developer.cognos.com/schemas/bmt/60/7}filter"/>
 *           &lt;element ref="{http://www.developer.cognos.com/schemas/bmt/60/7}calculation"/>
 *           &lt;element ref="{http://www.developer.cognos.com/schemas/bmt/60/7}dimension"/>
 *           &lt;element ref="{http://www.developer.cognos.com/schemas/bmt/60/7}scopeRelationship"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sectionType", propOrder = {
    "folderOrFunctionOrNamespace"
})
@XmlSeeAlso({
    com.cognos.developer.schemas.bmt._60._7.NamespaceType.class
})
public class SectionType
    extends com.cognos.developer.schemas.bmt._60._7.ReportObjectType
{

    @XmlElements({
        @XmlElement(name = "folder", type = com.cognos.developer.schemas.bmt._60._7.SectionType.class),
        @XmlElement(name = "function", type = com.cognos.developer.schemas.bmt._60._7.FunctionType.class),
        @XmlElement(name = "namespace", type = com.cognos.developer.schemas.bmt._60._7.Namespace.class),
        @XmlElement(name = "object", type = com.cognos.developer.schemas.bmt._60._7.ObjectType.class),
        @XmlElement(name = "shortcut", type = com.cognos.developer.schemas.bmt._60._7.ShortcutType.class),
        @XmlElement(name = "querySubject", type = com.cognos.developer.schemas.bmt._60._7.QuerySubject.class),
        @XmlElement(name = "updateSubject", type = com.cognos.developer.schemas.bmt._60._7.QuerySubjectType.class),
        @XmlElement(name = "relationship", type = RelationshipType.class),
        @XmlElement(name = "relationshipShortcut", type = com.cognos.developer.schemas.bmt._60._7.RelationshipShortcutType.class),
        @XmlElement(name = "filter", type = com.cognos.developer.schemas.bmt._60._7.FilterType.class),
        @XmlElement(name = "calculation", type = com.cognos.developer.schemas.bmt._60._7.CalculationType.class),
        @XmlElement(name = "dimension", type = com.cognos.developer.schemas.bmt._60._7.Dimension.class),
        @XmlElement(name = "scopeRelationship", type = com.cognos.developer.schemas.bmt._60._7.ScopeRelationshipType.class)
    })
    protected List<Object> folderOrFunctionOrNamespace;

    /**
     * Gets the value of the folderOrFunctionOrNamespace property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the folderOrFunctionOrNamespace property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFolderOrFunctionOrNamespace().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link com.cognos.developer.schemas.bmt._60._7.SectionType }
     * {@link com.cognos.developer.schemas.bmt._60._7.FunctionType }
     * {@link com.cognos.developer.schemas.bmt._60._7.Namespace }
     * {@link com.cognos.developer.schemas.bmt._60._7.ObjectType }
     * {@link com.cognos.developer.schemas.bmt._60._7.ShortcutType }
     * {@link com.cognos.developer.schemas.bmt._60._7.QuerySubject }
     * {@link com.cognos.developer.schemas.bmt._60._7.QuerySubjectType }
     * {@link RelationshipType }
     * {@link com.cognos.developer.schemas.bmt._60._7.RelationshipShortcutType }
     * {@link com.cognos.developer.schemas.bmt._60._7.FilterType }
     * {@link com.cognos.developer.schemas.bmt._60._7.CalculationType }
     * {@link com.cognos.developer.schemas.bmt._60._7.Dimension }
     * {@link com.cognos.developer.schemas.bmt._60._7.ScopeRelationshipType }
     * 
     * 
     */
    public List<Object> getFolderOrFunctionOrNamespace() {
        if (folderOrFunctionOrNamespace == null) {
            folderOrFunctionOrNamespace = new ArrayList<Object>();
        }
        return this.folderOrFunctionOrNamespace;
    }

}
