//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 10:35:14 AM MDT 
//


package com.cognos.developer.schemas.bmt._60._7;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for securityDefinitionSetType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="securityDefinitionSetType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="refobj" type="{http://www.developer.cognos.com/schemas/bmt/60/7}refType" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://www.developer.cognos.com/schemas/bmt/60/7}viewref" maxOccurs="unbounded"/>
 *       &lt;/choice>
 *       &lt;attribute name="includeRule" default="include">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="include"/>
 *             &lt;enumeration value="hide"/>
 *             &lt;enumeration value="exclude"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "securityDefinitionSetType", propOrder = {
    "refobj",
    "viewref"
})
public class SecurityDefinitionSetType {

    protected List<String> refobj;
    protected List<String> viewref;
    @XmlAttribute(name = "includeRule")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String includeRule;

    /**
     * Gets the value of the refobj property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the refobj property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRefobj().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getRefobj() {
        if (refobj == null) {
            refobj = new ArrayList<String>();
        }
        return this.refobj;
    }

    /**
     * Gets the value of the viewref property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the viewref property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getViewref().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getViewref() {
        if (viewref == null) {
            viewref = new ArrayList<String>();
        }
        return this.viewref;
    }

    /**
     * Gets the value of the includeRule property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncludeRule() {
        if (includeRule == null) {
            return "include";
        } else {
            return includeRule;
        }
    }

    /**
     * Sets the value of the includeRule property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncludeRule(String value) {
        this.includeRule = value;
    }

}
