//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 10:35:14 AM MDT 
//


package com.cognos.developer.schemas.bmt._60._7;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for shortcutType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="shortcutType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.developer.cognos.com/schemas/bmt/60/7}reportObjectType">
 *       &lt;sequence>
 *         &lt;element name="refobj" type="{http://www.developer.cognos.com/schemas/bmt/60/7}refType"/>
 *         &lt;element name="targetType" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN"/>
 *         &lt;element name="treatAs" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *               &lt;enumeration value="reference"/>
 *               &lt;enumeration value="alias"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="useInJoinPath" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "shortcutType", propOrder = {
    "refobj",
    "targetType",
    "treatAs",
    "useInJoinPath"
})
public class ShortcutType
    extends com.cognos.developer.schemas.bmt._60._7.ReportObjectType
{

    @XmlElement(required = true)
    protected String refobj;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String targetType;
    @XmlElement(defaultValue = "reference")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String treatAs;
    @XmlElement(defaultValue = "false")
    protected Boolean useInJoinPath;

    /**
     * Gets the value of the refobj property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefobj() {
        return refobj;
    }

    /**
     * Sets the value of the refobj property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefobj(String value) {
        this.refobj = value;
    }

    /**
     * Gets the value of the targetType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetType() {
        return targetType;
    }

    /**
     * Sets the value of the targetType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetType(String value) {
        this.targetType = value;
    }

    /**
     * Gets the value of the treatAs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTreatAs() {
        return treatAs;
    }

    /**
     * Sets the value of the treatAs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTreatAs(String value) {
        this.treatAs = value;
    }

    /**
     * Gets the value of the useInJoinPath property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUseInJoinPath() {
        return useInJoinPath;
    }

    /**
     * Sets the value of the useInJoinPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseInJoinPath(Boolean value) {
        this.useInJoinPath = value;
    }

}
