//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 10:35:14 AM MDT 
//


package com.cognos.developer.schemas.bmt._60._7;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for statusType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="statusType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="valid"/>
 *     &lt;enumeration value="invalid"/>
 *     &lt;enumeration value="needsReevaluation"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "statusType")
@XmlEnum
public enum StatusType {


    /**
     * Specifies that the syntax of the object is valid.
     * 
     */
    @XmlEnumValue("valid")
    VALID("valid"),

    /**
     * Specifies that the syntax of the object is not valid.
     * 
     */
    @XmlEnumValue("invalid")
    INVALID("invalid"),

    /**
     * Specifies that the object syntax needs to be reviewed.
     * 
     */
    @XmlEnumValue("needsReevaluation")
    NEEDS_REEVALUATION("needsReevaluation");
    private final String value;

    StatusType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static com.cognos.developer.schemas.bmt._60._7.StatusType fromValue(String v) {
        for (com.cognos.developer.schemas.bmt._60._7.StatusType c: com.cognos.developer.schemas.bmt._60._7.StatusType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
